### ISSUE TITLE
iqtree-omp built with gcc/5.2.0 consistently crashes

### ISSUE THREAD

**Issue by moskalenko** [Cibiv/IQ-TREE#1]
iqtree-omp -s input.fa -spp parts.nex -m GTR+G -bo 1 -wbt -seed $RANDOM -pre boot_1 -nt 16

builds without errors, but consistently crashes at the same stage. Prebuilt binary segfaults immediately with 'FATAL: kernel too old' on RHEL 6 - 2.6.32-504.30.3.el6.x86_64 kernel.

===> START BOOTSTRAP REPLICATE NUMBER 1

Creating bootstrap alignment (seed: 14945)...

Create initial parsimony tree by phylogenetic likelihood library (PLL)... 13.961 seconds

NOTE: 11387 MB RAM is required!
STACK TRACE FOR DEBUGGING:
1   double* aligned_alloc<double>(unsigned long)
2   PhyloSuperTreePlen::initializeAllPartialLh()
3   runTreeReconstruction(Params&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, IQTree&, std::vector<ModelInfo, std::allocator<ModelInfo> >&)
4   runStandardBootstrap(Params&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, Alignment*, IQTree*)
5   runPhyloAnalysis(Params&, Checkpoint*)
6   main()
7   __libc_start_main()
ERROR: Not enough memory, allocation of 881796096 bytes failed (bad_alloc)

**Comment by bqminh** [comment]
Hi there, thanks for your report. 
1. The prebuilt binary was statically built on Linux kernel 3.0. Thus this "kernel too old" problem was known. I don't know how to easily overcome this as we don't have a 2.6 Linux kernel anymore.
2. That last message is relevant:
"ERROR: Not enough memory, allocation of 881796096 bytes failed (bad_alloc)"
Here iqtree could not allocate memory and thus aborted. Does your machine have >11GB? See the above notice:
"NOTE: 11387 MB RAM is required!"

Minh

**Comment by moskalenko** [comment]
Hi. The machine has 128gb of memory. That's not the issue. Subsequent testing showed that zlib-1.2.3 worked, but using zlib-1.2.8 would result in a crash, so this is a zlib-specific problem.

**Comment by bqminh** [comment]
thanks for isolating the problem. As I don't have any idea what that problem is, it will be great if you can find out more about the cause. Right now the iqtree code includes a copy of zlib 1.2.7 (which is compiled if zlib is not available from the system) and I was thinking about upgrading to 1.2.8. Thus it will be helpful to fix the problem beforehand.

Minh

**Comment by moskalenko** [comment]
It turned out to be an issue with the scheduler propagating a small user limit value causing malloc calls to fail.
