### ISSUE TITLE
Dot syntax to represent alignment length in partition file

### ISSUE THREAD

**Issue by bqminh** [Cibiv/IQ-TREE#100]
I wonder if there is a good way to simplify the syntax for partitioning by codon when one has hundreds or thousands of alignments. Instead of looking up the length of each alignment, to use a wildcard character for the alignment length. I think the syntax below, with a `dot` as a placeholder for the length of the alignment, worked in Paup and MrBayes, but doesn't in IQTree (integer is required). Are there any tricks for doing something similar in IQTree? If not, can a feature like this be implemented. 

#nexus
begin sets;
    charset part1 = 1-.\3;
    charset part1 = 2-.\3;
    charset part1 = 3-.\3;
    ...
end;

Thanks,
Teo

**Comment by teofiln** [comment]
Thanks @bqminh!

**Comment by bqminh** [comment]
Done in commit abb6b6e3aba, to be released in v1.6.11
