### ISSUE TITLE
ERROR: pllPartitionsValidate v1.7 beta16

### ISSUE THREAD

**Issue by coyotree** [Cibiv/IQ-TREE#106]
Hello,

I am using the v1.7 beta16 on a computing cluster. I am using the -p command to point iqtree to a directory of alignment files. I keep getting the following error at the bottom the out file:

`330     DNA     71      295     73      147             trimalAUTO_7367_alignment.fasta
331     DNA     46      144     37      90              trimalAUTO_7371_alignment.fasta
332     DNA     82      747     206     352             trimalAUTO_7572_alignment.fasta
333     DNA     82      405     95      216             trimalAUTO_7577_alignment.fasta
334     DNA     62      97      17      60              trimalAUTO_7602_alignment.fasta
335     DNA     61      206     60      98              trimalAUTO_7628_alignment.fasta
Degree of missing data: 0.187
Info: multi-threading strategy over partitions

ERROR: pllPartitionsValidate`

My command is:
`iqtree -p /directory -st DNA -nt $SLURM_CPUS_ON_NODE -bb 1000 --prefix exon.concat`

I am loading cuda/9.2.88 intel/2018.1.163 openmpi/3.1.2

Not sure if that is a bug or if I am doing something wrong. Just wanted to let you know.

Thanks for this awesome work!

Cody Coyotee

**Comment by bqminh** [comment]
Hi Cody,

Thanks for the report. It looks like a bug. Can you please rerun adding -t PARS option to avoid PLL. Let me know if that works or not.

Minh

**Comment by coyotree** [comment]
Hi Minh,

That appears to have worked!

Cody
