### ISSUE TITLE
Model topologies

### ISSUE THREAD

**Issue by moibernabeu** [Cibiv/IQ-TREE#112]
Hi! I'm new! And I want to compare topologies of several models for a class. I would like to know if there is any possibility of writing trees of different models computed by IQ-Tree in an output file. I'm currently using both 1.6.12 and 2.0 versions.

ProtTest allows to export the individual models trees.

Thank you!!

**Comment by bqminh** [comment]
By default IQ-TREE uses one tree topology to test the model. But if you use -mtree option to find a tree for each model, then you can look at the checkpoint file .model.gz. That store for each model: the likelihood, degree of freedom, tree len and the tree topology in compact format, there sequence name is replaced by ID (from 0 to n-1, where n is number of sequences).
