### ISSUE TITLE
BNNI failure? IQ-Tree v2.0-rc1

### ISSUE THREAD

**Issue by coyotree** [Cibiv/IQ-TREE#113]
Hello,

I'm trying to use the bnni function with ufboot and it appears to keep failing. I'm not entirely sure. Error file says to submit the log files and alignment (if possible). Log file is attached. Let me know if you would like the alignment as well.

Thank you!

[exon.gene.bnni.concat.log](https://github.com/Cibiv/IQ-TREE/files/4032083/exon.gene.bnni.concat.log)

**Comment by bqminh** [comment]
Can you pls try with v2.0-rc2 again?

**Comment by bqminh** [comment]
I the mean time we have found the bug and fixed it. For the moment please use -keep_empty_seq option, whenever you use `--sampling GENE` or `--sampling GENESITE` option. 
Thanks

**Comment by bqminh** [comment]
Fixed in v2.0.6
