### ISSUE TITLE
Nonparametric bootstrap gene trees using -S option

### ISSUE THREAD

**Issue by coyotree** [Cibiv/IQ-TREE#114]
Hello,

I am attempting to use the -S option on a directory of gene alignments, and I would like support values on each of the resulting gene trees. This worked when using UFBoot but I keep getting a segmentation fault when attempting to use nonparametric bootstrapping (-b). I am using v2.0-rc1. Log file attached. 
Any thoughts appreciated.

[exon.nonparaboot.loci.with.support.log](https://github.com/Cibiv/IQ-TREE/files/4083830/exon.nonparaboot.loci.with.support.log)

Thank you!
Cody

**Comment by bqminh** [comment]
-b option (nonparametric bootstrap) does not work with -S option yet... So pls avoid combining these for now! Thanks
