### ISSUE TITLE
Obtain CI for parameter estimates?

### ISSUE THREAD

**Issue by sjspielman** [Cibiv/IQ-TREE#119]
Hi @bqminh , 

I'm wondering if there is any way in IQ-TREE to obtain 95% CI or similar from parameter estimates. (I am particular interested in seeing CI's for protein GTR model exchangeabilities, but I suspect implementation would be similar for any model w/ optimized parameters). Is this information currently somewhere in IQ-TREE output, or do you have any suggestions for how I can get this info, or any chance this could be a future feature? :)

Thanks very much!
-Stephanie

**Comment by bqminh** [comment]
The answer is currently there is no such feature.

@sjspielman how do you compute the CI of a parameter? Do you have an exact formula here?
