### ISSUE TITLE
AICc calculation (query?)

### ISSUE THREAD

**Issue by mdhall272** [Cibiv/IQ-TREE#121]
Hi,

The formula for AICc in the code (phylotesting.cpp, line 331) is:

```
AICc = AIC + 2.0 * df * (df + 1) / max(ssize - df - 1, 1);
```
i.e., if the denominator of the penalty term, according to the standard formula, is negative it is instead set to 1.

Perhaps this is the intended behaviour, but I wanted to double check. On trees I've been running, AICc results are dramatically different to the other two ICs (preferring vanilla JC models where the others like very highly-parameterised GTR variants).

**Comment by bqminh** [comment]
Great question! In my memory, before the time IQ-TREE didn't have max() function and the AICc looks really weird (or even negative). That's I introduced in max() to avoid this, but I admit it's very ad-hoc. In my opinion AICc should not be used when sample size < df. Perhaps in such case, AICc should be NA to warn users. 
What do you think? Or do you it should be without max()?
