### ISSUE TITLE
Don't replace odd characters in sequence names with underscores

### ISSUE THREAD

**Issue by rambaut** [Cibiv/IQ-TREE#122]
Please allow more characters in sequence names. In particular '|' are often use to denote fields. Replacing them with underscores causes problems because underscores are used to denote spaces.

**Comment by bqminh** [comment]
Done, with commit a37ba6258 (in v2.0)

**Comment by rambaut** [comment]
Is it possible to leave other punctation marks as they are? I.e.,  `/`, `@`, etc.? Is there a need to convert any character but whitespace?

**Comment by bqminh** [comment]
I just manually allowed `|` character. Allowing `/` caused a crash in the phylogenetic likelihood library (PLL). Will try to have a more robust solution, e.g., when interfacing with some libraries, internally use the taxon IDs instead of names...

**Comment by bqminh** [comment]
Btw, which characters in the names do yow allow/disallow in BEAST?
Then I'll use the same.
I guess the following are not allowed: `(`, `)`, `[`, `]`, `,`, `:`, `;`. What else?

**Comment by rambaut** [comment]
Anything is allowed - if there are any characters like this or space they are put in quotes.

**Comment by bqminh** [comment]
At least I now allow both slash and bar characters in the sequence name. So it should work for the virus dataset. This will be released in v2.0.4 (including some hot fix in v2.0.3)

**Comment by rambaut** [comment]
Thanks Minh, much appreciated.

**Comment by johannahelene** [comment]
Hello, I was wondering if it was possible to leave the `#` as it is in sequence names and not have it change to an underscore?
