### ISSUE TITLE
Question re +ASC option

### ISSUE THREAD

**Issue by mearls999** [Cibiv/IQ-TREE#123]
Hi,

I'm running IQTree with the snippy-core output of ~200 staph aureus isolates like so: 

iqtree -s core.aln -m GTR+ASC

The tree is turning out pretty much as expected, however, I'm wondering how IQTree knows how to correct the branch scale if I never told it the number of invariant sites. Any help would be much appreciated.

Thanks,

Megan

**Comment by bqminh** [comment]
This questions was asked and answered in the forum
