### ISSUE TITLE
IQ-TREE CRASHES WITH SIGNAL ABORTED

### ISSUE THREAD

**Issue by MarHayat** [Cibiv/IQ-TREE#124]
Hi 

I am going to use IQ-TREE version 1.6.12 to reconstruct a tree. I use this command:

bin/iqtree -s /home/alignment_withRef.fasta -m GTR+F+I+G4 -nt AUTO
 
after 1 day and a half running on a cluster it crashed with this error:

Computing ML distances based on estimated model parameters...ERROR: STACK TRACE FOR DEBUGGING:
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
 Here is the end of the log file:
For your convenience alignment with unique sequences printed to /home/alignment_withRef.fasta.uniqueseq.phy

Create initial parsimony tree by phylogenetic likelihood library (PLL)... 2897.813 seconds

NOTE: 10255 MB RAM (10 GB) is required!
Measuring multi-threading efficiency up to 32 CPU cores
2 trees examined
Threads: 1 / Time: 2272.096 sec / Speedup: 1.000 / Efficiency: 100% / LogL: -5262762
Threads: 2 / Time: 1883.907 sec / Speedup: 1.206 / Efficiency: 60% / LogL: -5262762
Threads: 3 / Time: 1881.949 sec / Speedup: 1.207 / Efficiency: 40% / LogL: -5262762
BEST NUMBER OF THREADS: 2

Estimate model parameters (epsilon = 0.100)
Thoroughly optimizing +I+G parameters from 10 start values...
Init pinv, alpha: 0.000, 1.000 / Estimate: 0.072, 0.804 / LogL: -509689.859
Init pinv, alpha: 0.008, 1.000 / Estimate: 0.072, 0.805 / LogL: -509690.995
Init pinv, alpha: 0.016, 1.000 / Estimate: 0.072, 0.805 / LogL: -509692.505
Init pinv, alpha: 0.024, 1.000 / Estimate: 0.072, 0.805 / LogL: -509693.784
Init pinv, alpha: 0.033, 1.000 / Estimate: 0.072, 0.805 / LogL: -509695.035
Init pinv, alpha: 0.041, 1.000 / Estimate: 0.072, 0.805 / LogL: -509696.122
Init pinv, alpha: 0.049, 1.000 / Estimate: 0.072, 0.805 / LogL: -509697.449
Init pinv, alpha: 0.057, 1.000 / Estimate: 0.072, 0.805 / LogL: -509698.933
Init pinv, alpha: 0.065, 1.000 / Estimate: 0.072, 0.805 / LogL: -509700.317
Init pinv, alpha: 0.073, 1.000 / Estimate: 0.072, 0.805 / LogL: -509701.701
Optimal pinv,alpha: 0.072, 0.804 / LogL: -509689.859

Parameters optimization took 105476.427 sec
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Computing ML distances based on estimated model parameters...ERROR: STACK TRACE FOR DEBUGGING:
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: /home/alignment_withRef.fasta.log
ERROR: ***    Alignment files (if possible)
/var/spool/slurmd/job39136899/slurm_script: line 18: 23105 Aborted                 (core dumped) bin/iqtree -s /home/alignment_withRef.fasta -m GTR+F+I+G4 -nt AUTO

Can you please let me know how should I fix this error?

Thanks

**Comment by bqminh** [comment]
The bad_alloc means that IQ-TREE cannot allocate enough RAM in your computer for itself. Perhaps make sure that other processes in your cluster do not take too much RAM. Many processes using a lot of RAM may interfere with each other...

**Comment by MarHayat** [comment]
Thanks for your response. I have around 26G available ram on a cluster. Do you think this amount is enough to reconstruct a tree with 66000 tips (the length of each sequence is 1700)?

**Comment by bqminh** [comment]
Ah OK, I didn't know that you have 66K tips, and that explains now. At this step, IQ-TREE computes the pairwise distance matrix, which has a size of n^2, where n=#sequences. Each entry is a double floating point number, which needs 8 bytes. Therefore, you need 8*n^2 bytes of RAM. In your case, that is ~34 GB. Plus 10 GB RAM required as noted earlier, so you need at least 34+10 =44 GB RAM.

OR: you can avoid the pairwise distance (and the BIONJ tree) and also use the fast search option to speed up computation. To that, please add "-fast -ninit 1" into the command line.
