### ISSUE TITLE
Error: Argument of option -a must be an integer.

### ISSUE THREAD

**Issue by Cactusolo** [Cibiv/IQ-TREE#128]
Hi,

I used iqtree for tip dating.

my cmd is `iqtree -s full.fasta -o outgroup --date full_date.tsv --date-root 2013-07-24 --date-tip 2020-03-26 -nt AUTO `

as it explained in the manual that:
TIME TREE RECONSTRUCTION:
  --date FILE          Dates of tips or ancestral nodes
  --date TAXNAME       Extract dates from taxon names after last '|'
  --date-tip STRING    Tip dates as a real number or YYYY-MM-DD
  --date-root STRING   Root date as a real number or YYYY-MM-DD
  --dating STRING      Dating method: LSD for least square dating (default)

**However, I got error message as below:**  
Reading date file full_date.tsv ...
1396 dates extracted
Building time tree by least-square dating (LSD) with command:
**_lsd -i full.fasta.timetree.subst -s 29891 -c -o full.fasta.timetree -g full.fasta.timetree.outgroup -d full.fasta.timetree.date -a 2013-07-24 -z 2020-03-26 
Error: Argument of option -a must be an integer._**

**Comment by bqminh** [comment]
Thanks for testing it so quickly, I have fixed this. So please re-download v2.0.3. Moreover, I also wrote a tutorial for how to use this feature here: http://www.iqtree.org/doc/Dating and officially announced it in the IQ-TREE forum.

Let me know if that works for you now.

**Comment by Cactusolo** [comment]
@bqminh Hi,
I've reran the analyses, it give me another error again. It seems iqtree not able to recognize the tree generated by its own?

I used cmd: `iqtree -s full.fasta -o "OG1,OG2" --date full_date.tsv -nt AUTO`
the error msg:
     ...
Analysis results written to: 
  IQ-TREE report:                full.fasta.iqtree
  Maximum-likelihood tree:       full.fasta.treefile
  Likelihood distances:          full.fasta.mldist
  Screen log file:               full.fasta.log

Reading date file full_date.tsv ...
1397 dates extracted
Building time tree by least-square dating (LSD) with command:
lsd -i full.fasta.timetree.subst -s 29891 -c -o full.fasta.timetree -g full.fasta.timetree.outgroup -d full.fasta.timetree.date 
Removing outgroups of tree 1 ...

TREE 1
*PROCESSING:
Reading the tree ... 
**### ERROR: Error in the file input tree**

**Comment by bqminh** [comment]
Can you pls send me the input files (alignment and date file) for debugging purpose? Use my email minh.bui@univie.ac.at if confidential.
Thanks

**Comment by bqminh** [comment]
This looks like a bug in LSD2 code, not in IQ-TREE. I sent the information to the LSD2 author for debugging purpose.
