### ISSUE TITLE
IQ-TREE does not compile on NetBSD

### ISSUE THREAD

**Issue by njoly** [Cibiv/IQ-TREE#13]
Hi,

Just wanted to compile latest IQ-TREE on NetBSD but it failed to link the iqtree binary

[...]
[100%] Linking CXX executable iqtree
CMakeFiles/iqtree.dir/tools.cpp.o: In function `print_stacktrace(std::ostream&, unsigned int)':
/home/njoly/temp/IQ-TREE/tools.cpp:4054: undefined reference to `backtrace'
/home/njoly/temp/IQ-TREE/tools.cpp:4063: undefined reference to `backtrace_symbols'
--- iqtree ---
*** [iqtree] Error code 1

On some systems the backtrace functions are provided by libC, but on NetBSD they are located in their own library "libexecinfo.so"

Adding a check for the "Backtrace" package in CMakeList.txt, fixes the problem.

find_package(Backtrace)
target_link_libraries(iqtree ${Backtrace_LIBRARY})

Thanks in advance.

**Comment by bqminh** [comment]
Hi @njoly , thanks for the info, as I have never compiled iqtree for this platform. Before I add this check into the master branch, can you help me to make sure that it works also for Linux, Mac and Windows? That means, to introduce condition like:
if (NetBSD)
 ...
endif()
I just don't know to set such NetBSD variable in CMake.
And finally to simplify, can you create a pull request for the change?
Thanks, Minh

**Comment by njoly** [comment]
Hi,

Adding such specific conditionals should be avoided for greater portability ... AFAIK "find_package(Backtrace)" should do no harm on every systems. And then, conditionals could be done with "Backtrace_FOUND" both in CMakeList.txt and tools.cpp.

I'll check on platforms i have access to, which include NetBSD, Linux and Mac. Unfortunately, i don't have any Windows platform. If you're ok, i'll submit a pull request.

Thanks.

**Comment by bqminh** [comment]
yes can you pls submit the pull request? I can check it on Windows. Thanks!

**Comment by bqminh** [comment]
merged! thanks a for for the fix.
