### ISSUE TITLE
v2.0.3 build failures 

### ISSUE THREAD

**Issue by Jehops** [Cibiv/IQ-TREE#130]
Hello,

We are seeing an issue with include files when building v2.03: `/wrkdirs/usr/ports/biology/iqtree/work/IQ-TREE-2.0.3/main/timetree.cpp:9:10: fatal error: lsd2/src/lsd.h: No such file or directory`

[Here is a full build log.](http://pkg.awarnach.mathstat.dal.ca/data/12amd64-default/2020-04-24_21h04m33s/logs/errors/iqtree-2.0.3.log)

This is on FreeBSD versions 11.3 and 12.1 i386 and amd65.

**Comment by bqminh** [comment]
Thanks! this is now fixed and will be released in v2.0.4
Please note that if you are after the new phylo dating feature, then you need to get the code from GitHub:

git clone --recursive https://github.com/Cibiv/IQ-TREE.git
cd IQ-TREE
git checkout latest
git submodule update

to download the source code with the LSD2 module.

And at the cmake step, add -DUSE_LSD2=ON to the cmake command in the build folder:

cmake -DUSE_LSD2=ON <SOURCE_DIR>

**Comment by tseemann** [comment]
I hoped `cmake -DUSE_LSD2=` would get around this but it did not.

**Comment by bqminh** [comment]
Just released the fix version 2.0.4, pls check it out
