### ISSUE TITLE
Detected only 1 node when I called 3 on a cluster with slurm

### ISSUE THREAD

**Issue by depengl** [Cibiv/IQ-TREE#133]
Hello,
I use following commend  on a cluster and assigned total 40 CPU cores from 3 nodes. While iqtree(the latest version) can only detect 16 cores from one node.  I wonder can iqtree take full advantage of all the 40 cores from different nodes?

Thank you so much!

Depeng

#!/bin/bash
#SBATCH --partition=largemem #queue
#SBATCH --job-name=iqtree_1_ingo_m1
#SBATCH --ntasks=40

iqtree2 -p iqtree_all.nex -m MFP+MERGE -rcluster 10 -cptime 600 --prefix apr28_tree -nt AUTO

**Comment by depengl** [comment]
I am trying to compile a mpi version but there are some errors from cluster. Can I use mpiprun iqtree2 directly?

**Comment by bqminh** [comment]
The simple answer is no, right now the MPI version can only work under the scenario, that all processes will have the same number of threads.
