### ISSUE TITLE
phylogenetic dating timetree error IQTREE2

### ISSUE THREAD

**Issue by ekamau** [Cibiv/IQ-TREE#135]
Been trying to infer time tree with iqtree2 and I keep getting the error:
' **timetree.cpp:204: void writeDate(std::__cxx11:string, std::ostream &, StrVector &): Assertion `0 && "Error writing date stream"' failed.** 
IQ-TREE CRASHES WITH SIGNAL ABORTED
'
I have no idea what this means.
This happens after Analysis results written to files: *.iqtree, *.treefile, *.mldist, *.log

I am using Linux/ubuntu.
I can provide a log file with the stack trace if required.

Any solutions or ideas? Thank you.

**Comment by pveber** [comment]
same problem here!

**Comment by roblanf** [comment]
Hi both thanks for reporting this.

Can you try downloading the latest release and trying again? 

https://github.com/Cibiv/IQ-TREE/releases/tag/v2.0.5

If you get the same error, please just post back here with log files and as much detail as possible about your input data too.

**Comment by bqminh** [comment]
I believe this is because your dates are not in the right format (YYYY-MM-DD). So pls check them carefully. In v2.0.5 I have changed the error message, to print out this specifically, instead of this crash message.

Minh

**Comment by ekamau** [comment]
Thank you for the response.

I will download again and try change the date format.
I previously had dd-MMM-YYYY. Hope it works now.

Everlyn

**Comment by ekamau** [comment]
I had the dates in the wrong format.
YYYY-MM-DD works.

Great!

**Comment by pveber** [comment]
I confirm it was the same problem for me, one date had "XX" instead of actual numbers. Thanks a lot for the fix!
