### ISSUE TITLE
ERROR: You must specify the number of taxa in the PD set.

### ISSUE THREAD

**Issue by Cactusolo** [Cibiv/IQ-TREE#136]
Hi,

In the simple tutorial [here](http://www.iqtree.org/doc/Dating), it says "If you already have a tree, you can use option -te TREE_FILE to ask IQ-TREE to load and fix this tree topology. " so I did:
`iqtree2 -te inputtreei --date date.tsv -nt AUTO`
it gave error as:
**ERROR: You must specify the number of taxa in the PD set.** What is "PD set"? What does this mean? Do I need to provide alignment as well?

Thanks!

Miao

**Comment by bqminh** [comment]
You also need to input an alignment.
Minh

**Comment by Cactusolo** [comment]
@bqminh Thanks! It worked.

Another question, does current version of iqtree provide the feature that I can obtain 95% CI dating for each nodes?

Thanks!

Miao

**Comment by bqminh** [comment]
Yes you can,

please add: --date-options “-f 1000” to the command line. 

This will perform 1000 samplings to estimate CI, assuming a log-normal relaxed clock with mean of 1 and std-dev 0.2. 

If you open in FigTree, select "Node Labels” tab and choose Display as CI_date. The CI will be noted in bracket for every ancestral node.

--date-options is to pass additional options to LSD2, which is "-f 1000" in this case. I will make an explicity option in IQ-TREE for that.

Minh

**Comment by Cactusolo** [comment]
@bqminh beautiful!! Thanks!!
It would attract much wider users, if more detailed features explained [here](http://www.iqtree.org/doc/Dating). Or did you posted other pages?
