### ISSUE TITLE
Full genome alignment vs using -fconst

### ISSUE THREAD

**Issue by gkarthik** [Cibiv/IQ-TREE#137]
Hello,

I've been looking into speeding up some iqtree runs by supplying the invariant sites using `-fconst`. The alignment has 1045 variable sites and ~28700 invariant sites.

This is the command I'm using with `-fconst`
```
iqtree -s $algn -bb 1000 -nt 6 -alrt 1000 -m TEST -fconst $constsites
```

and this is the one without `-fconst`

```
iqtree -s $algn -bb 1000 -nt 6 -alrt 1000 -m TEST
```

The run with the full genome alignment (~30000 bps) takes 2h:24m:37s while with `-fconst` the runs takes only `0h:17m:7s`. 

However, the topology of the trees with `-fconst` is very different from the topology of the tree generated using the full genome alignment. I wanted to clarify if I am using the `-fconst` parameter correctly. 

I'm using `iqtree v1.6.11` on `Ubuntu 16.04`. 

Thank you!

**Comment by bqminh** [comment]
You have to use -fconst fA,fC,fG,fT

where fA is the number of constant site of A…A. And so on. 

It is not clear from your command line, but I assume you supply a single number of invariant sites to -fconst. This is not valid.

Minh

**Comment by gkarthik** [comment]
I do supply 4 numbers: `fA,fC,fG,fT` to `-fconst` each indicating the number of constant columns for each nucleotide to be added.

**Comment by bqminh** [comment]
How did you count these? 

Please note that invariant sites with “A" and “-“ should not be discarded from the alignment. fA should only count the number of AAAAA sites, i.e. strictly with A character. And not including A-A--AA, for example.

**Comment by gkarthik** [comment]
I use `snp-sites -C` to get the counts for `-fconst` and `snp-sites -c` to get the columns without gaps, Ns etc as input to `iqtree -s`. The manual says it only excludes AAAA and not A-AA etc.
 
```
 -C     only output count of constant sites (suitable for IQ-TREE -fconst) and nothing else
```

[snp-sites repo](https://github.com/sanger-pathogens/snp-sites)
