### ISSUE TITLE
The tree reconstructed from IQ-tree is not rooted

### ISSUE THREAD

**Issue by MarHayat** [Cibiv/IQ-TREE#138]
Hi,

I am using this command on  IQ-tree2  to reconstruct a rooted phylogenetic tree:

bin/iqtree2 -s ~/alignment.fasta -m GTR+F+G4 -nt AUTO -o A/Netherlands/209/1980--EPI_ISL_114198--A_/_H3N2--12/01/1980  -fast -ninit 1

The reconstructed tree is not rooted. Do I need to add other options to get a rooted tree?

Thanks

**Comment by bqminh** [comment]
Please look at the IQ-TREE google group, this was discussed and answered there.
