### ISSUE TITLE
ERROR: There are at least two leaves that have the same label

### ISSUE THREAD

**Issue by MANaranjo** [Cibiv/IQ-TREE#139]
Hello,
I'm trying the new tree dating function in IQTree2. However, I keep getting an error saying that I have more than one leaf with the same label during the tree processing step. I have tried modifying the names of the species in the alignment, the file with calibration points and even providing a guide tree, but I keep getting the same error.

**Comment by santiak** [comment]
I have the same problem

**Comment by bqminh** [comment]
Sorry, I can’t help here if I don’t know the context. Please send at least the command line and log file.

**Comment by santiak** [comment]
I hope this helps. Thanks!
[partition.nex.log](https://github.com/Cibiv/IQ-TREE/files/4672383/partition.nex.log)

**Comment by bqminh** [comment]
Ok, thanks, now I see the problem, that it happened in the dating step. If you had reported that earlier, then it'd be easier to debug.

@tothuhien can you pls help here? The error message occurred within LSD (see log file above). But that does not make sense, because if two leaves have the same label, IQ-TREE would not run in the first place. 
Thanks!

**Comment by tothuhien** [comment]
Hi, this can happen for both leaves and internal nodes. To see which node label caused the problem,  could you send me the date file and the tree file (tothuhien@gmail.com) if possible? I'll have a look at that.
Hien

**Comment by bqminh** [comment]
To help debug: @santiak please rerun iqtree with `--date-debug` option, which will print two additional files ending .timetree.subst and .timetree.date. Please send these two files to @tothuhien for debugging. The command line to run lsd is printed in iqtree log file.
Thanks!

**Comment by bqminh** [comment]
The date file is not in the right format, with empty space in the comma-separated list of taxon names. Please try v2.0.6 that does better error checking with informative messages.

**Comment by bqminh** [comment]
Fixed
