### ISSUE TITLE
IQ-TREE 2 not running dating from Conda

### ISSUE THREAD

**Issue by conmeehan** [Cibiv/IQ-TREE#143]
Hi,

When I install IQ-TREE 2.0.3 using conda on linux, I cannot run the dating as it was not compiled with the LSD library. I get the following error:
IQ-TREE was not compiled with LSD2 library, rerun cmake with -DUSE_LSD2=ON option

Is there a way to have the conda version be dating enabled so i dont have to have separate installations please?

Thanks,
Conor

**Comment by bqminh** [comment]
Hi Conor,

Can you please ask the conda people to change that? Actually I don’t know who created this conda package. Also tell them to use the latest version 2.0.5, as it has feature to compute confidence intervals for the date estimates.

Thanks,
Minh
