### ISSUE TITLE
iqtree partition file

### ISSUE THREAD

**Issue by lalalagartija** [Cibiv/IQ-TREE#153]
Hi ! 
How do I generate a partition file readable by iqtree ? 
Here is what my partition file looks like : 
protein, part1 = 1-1506
protein, part2 = 1507-2991
protein, part3 = 2992-5177
protein, part4 = 5178-7510
protein, part5 = 7511-7688
protein, part6 = 7689-8250

I want Iqtree to choose the best model for each partition so I didn't added it to the file. Each time I got this error 
`CHECKPOINT: Initial tree restored
ERROR: File not found protein`
when I tried `iqtree -spp clipkit_allseqs.partitions.txt  -s clipkit_allseqs.fas `
and eventually I want to achieve : 
`iqtree -spp clipkit_allseqs.partitions.txt  -s clipkit_allseqs.fas  --prefix pithos_metag_important_genes_clipkit -bb 1000 -bi 50`

Thank you in advance,

**Comment by lalalagartija** [comment]
I understood after that I can't have "protein" as first argument but I have to give an actual model. Is there no option to let iqtree choose the best model as it did in previous versions ?

**Comment by OlgaChern** [comment]
Hello,
you do need to specify the command to run model test, try adding -m MFP. And possibly also add -redo, so Iqtree does not read info from your previous runs.

Cheers,
Olga

**Comment by lalalagartija** [comment]
Thank you very much ! I am also trying the -m TESTONLY to see which models are tested but I do need to enter  something in my partition file. Now it looks like : 

LG+F+I+G4, DNApoll_clipkit-1 = 1-1506
LG+F+I+G4, DNApoll_clipkit-2 = 2-1506
LG+F+I+G4, DNApoll_clipkit-3 = 3-1506
LG+F+I+G4, mRNAcapping_clipkit-1 = 1507-2991
LG+F+I+G4, mRNAcapping_clipkit-2 = 1508-2991
...
are you saying that if type -m MFP iqtree does not take into account "LG+F+I+G4" and recalculates a model ? and will that model be different for every partition ?

**Comment by OlgaChern** [comment]
My test command line was:
iqtree -spp test.part -s aln.fasta -m MFP -redo

with partition file:
protein, part1 = 1-10
protein, part2 = 11-20

using -m MFP, iqtree selects best model per partition. 

But I realised, that I have an old iqtree version (1.6.12).. I guess, things might have changed since then. Just try running with -m MFP. Check the log file, to see if it ignores your pre-specified model. I think it should.

Cheers,
Olga

**Comment by lalalagartija** [comment]
Great ! Thank you !
