### ISSUE TITLE
 Segmentation fault with large sample size 

### ISSUE THREAD

**Issue by canyansi** [Cibiv/IQ-TREE#154]
I was able to run IQ-tree on my smaller set of samples (20 and then 5k) but have not been able to get it to work on a larger dataset. This is contents of log file:

IQ-TREE multicore version 1.6.12 for Linux 64-bit built Jun 18 2020
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.

Host:    ***** (AVX512, FMA3, 755 GB RAM)
Command: iqtree -nt 64 -s notmixed_oct31.fasta -bb 1000 -seed 0 -m GTR+F+ASC+R9 -pre nomix
Seed:    0 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Fri Jun 26 00:51:53 2020
Kernel:  AVX+FMA - 64 threads (64 CPU cores detected)

Reading alignment file notmixed_oct31.fasta ... Fasta format detected
Alignment most likely contains DNA/RNA sequences
Alignment has 42313 sequences with 91156 columns, 78544 distinct patterns
91156 parsimony-informative, 0 singleton sites, 0 constant sites

****  TOTAL          0.01%  0 sequences failed composition chi2 test (p-value<5%; df=3)
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL SEGMENTATION FAULT
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: nomix.log
ERROR: ***    Alignment files (if possible)

What should I do to solve the problem? I've given it more memory and lots of cores not sure what else I should do?

**Comment by bqminh** [comment]
I believe you posted this question in the forum, right? I'm closing it to avoid duplicate.
Just wanted to say: We're releasing a version soon to address computational issue with very large datasets like this.
