### ISSUE TITLE
[BUGS]  Memory required per CPU-core (24.1637 GB) is higher than your computer RAM per CPU-core

### ISSUE THREAD

**Issue by jzhan6** [Cibiv/IQ-TREE#157]
Dear Iqtree team

When I run iqtree_mpi version for both 1.X and 2.X, I got warning message 
WARNING: Memory required per CPU-core (24.1637 GB) is higher than your computer RAM per CPU-core (0 GB), thus multiple runs may exceed RAM!

the command is 
`/home2/jzhang/locals/IQ-TREE/build/iqtree-mpi -s alignments_posi0.8_new.aliscore -spp alignments_posi0.8_new.aliscore_codon_partitions -nt
 20 -pre alignments_posi0.8_new.aliscore_part_by_codon`  for version 1.6.12
or
`/work/00412/mtang/local/bin/iqtree2-mpi_ls5 -s alignments_posi0.8_new.aliscore -p alignments_posi0.8_new.aliscore_codon_partitions -T AUTO -nt 32 -pre alignments_posi0.8_new.aliscore_partition_by_codon`   for version 2.0

However for the node I usually have **_32GB or 64GB_** memory

I tried to use -mem but it is not compatible with partition analysis (-spp or -p)

Is it possible for me to make iqtree detect the all RAM or set memory for iqtree to run when there is partition file?

Sincerely,
Jing Zhang

**Comment by bqminh** [comment]
Please use the iqtree forum for this question, I've seen your question there.
