### ISSUE TITLE
Heterotachy model - fixing branch lengths

### ISSUE THREAD

**Issue by crotty** [Cibiv/IQ-TREE#16]
Option -blfix is not available for the heterotachy model. This means it is not possible to calculate the likelihood of the data on a specific tree. The error message received when trying to do this is:

ERROR: Fixing branch lengths is not supported under specified site rate model

**Comment by bqminh** [comment]
Hi Stephen, Indeed this can't be supported due to the technical implementation with the EM algorithm. So I will close this issue.
Minh
