### ISSUE TITLE
LSD error in divergence time estimation: Error: There's conflict or not enough signal in the input temporal constraints.

### ISSUE THREAD

**Issue by moveAFs** [Cibiv/IQ-TREE#160]
I recently estimated the divergence time of species in a tree using IQ-TREE v2.0.6 LSD with calibration fossil records, and it run into error, here the command:
```shell
iqtree2 -s alignment.fasta --date date.txt -te species.tree --date-ci 100 -nt 20 --date-tip 0
```
as you suggested in issue (https://groups.google.com/g/iqtree/c/eenid6U3kdQ) I also run this with --date-options "-u 0" parameter, but this do not solve the problem for me and generate the same error: 
> Error: There's conflict or not enough signal in the input temporal constraints.

this really confuse me, what cause the "conflict" or "not enough signal", here I attached related files (including alignment, date file and tree file)
[input.zip](https://github.com/Cibiv/IQ-TREE/files/5025977/input.zip)

what's more, in the log we see the LSD command use different file from my input, are these files the same as my input? I am not sure if it can be helpful for solving this error to keep these files?

**Comment by bqminh** [comment]
I believe this was fixed in the latest lsd2 incorporated in iqtree v2.1.1
