### ISSUE TITLE
Estimate of memory requirements

### ISSUE THREAD

**Issue by monomeric** [Cibiv/IQ-TREE#182]
Thanks for this amazing piece of software!

Is there any efficient way to accurately estimate memory requirements for a given alignment and given model parameters, without initiating a run of IQ-TREE? I would need to be able to do so to select which hardware to run a large phylogenetic job on. 

Is the memory complexity of IQ-TREE documented?

Best,
Mono

**Comment by bqminh** [comment]
Hi Mono,

This is not documented.

But roughly speaking, the RAM requirement in bytes is the product of 8 (eight), the number of sequences, sequence length, the number of states in the data (4 for DNA, 20 for amino-acid), the number of rate categories in the model (e.g., 4 if you use +G4 model), and the number mixture classes (e.g. 10 if you use +C10 mixture model).

Minh

**Comment by monomeric** [comment]
Hi Minh,

Thanks for the illustration. So the complexity of the base substitution rate model does not impact significantly on the memory requirements?

Mono

**Comment by bqminh** [comment]
I assume you are asking about something like whether using JC or GTR model has different memory requirement. If so, the answer is No, JC, GTR or any other substitution models will have the same RAM requirement.

Minh

**Comment by monomeric** [comment]
Thanks for the elaborations!
