### ISSUE TITLE
Error with partition model file

### ISSUE THREAD

**Issue by Mosy135** [Cibiv/IQ-TREE#185]
Hi, 
I'm using iqtree in conda to generate a tree with partition model, but I keep getting the same error message

> IQ-TREE multicore version 2.0.3 for Linux 64-bit built Apr 26 2020
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.
Host:    login (AVX2, FMA3, 125 GB RAM)
Command: iqtree -s 40taxa.phylip -p iqtreeparti.nex -T 8 -B 1000
Seed:    192950 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Tue Jan 19 16:35:28 2021
Kernel:  AVX+FMA - 8 threads (40 CPU cores detected)
Reading partition model file iqtreeparti.nex ...
ERROR:
ERROR: Error found at line 139, column 5 (file position 8937):
ERROR: Expecting ':' or ',' but found  instead

This partition code is generated by partitionfinder, and I chose the iqtree part. 
The partition model file is as follow, I have changed the extension from nex to txt due to github doesn't support nex format
[iqtreeparti.txt](https://github.com/Cibiv/IQ-TREE/files/5834630/iqtreeparti.txt)

I have tried to replace `;` in the end of file to `,` or `:` like what error message said , but it didn't work.

What should I do to fix this error ?

**Comment by OlgaChern** [comment]
Hi there!

you have a mistake in the format:

line "charpartition PartitionFinder” -> there must be “:” between the model and a partition name:

yours "GTR+I+GSubset1” and must be “GTR+I+G: Subset1” 

for all models/partitions

Cheers,
Olga

**Comment by Mosy135** [comment]
It works! Thanks for the help
