### ISSUE TITLE
Phylogenetic dating using a fixed rate

### ISSUE THREAD

**Issue by nicolettacommins** [Cibiv/IQ-TREE#193]
I have a dataset with time information but no appreciable temporal signal. I want to date the phylogeny using a separate clock rate estimate which is possible in BEAST. I'm interested in using a faster method and I'm wondering if there is any feature in IQ-TREE that allows the user to fix the clock rate without trying to estimate it?

**Comment by iqtree** [comment]
to be closed, this should be asked in the iqtree google group.
