### ISSUE TITLE
Core dumped error

### ISSUE THREAD

**Issue by cgy0627** [Cibiv/IQ-TREE#199]
Hello,

I keep getting the core dump error like the following:

```
NOTE: 45292 MB RAM (44 GB) is required!
WARNING: Memory required per CPU-core (44.2313 GB) is higher than your computer RAM per CPU-core (7 GB), thus multiple runs may exceed RAM!
CHECKPOINT: Model parameters restored, LogL: -8028756.6703802049
Best tree printed to 209species.Intact_gt0.1_RE.JTT.treefile
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Computing ML distances based on estimated model parameters...ERROR: STACK TRACE FOR DEBUGGING:
ERROR:
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: 209species.Intact_gt0.1_RE.JTT.log
ERROR: ***    Alignment files (if possible)
Aborted (core dumped)
```

My alignment contains 64,096 sequences that are 444 aa in length, and the computer has 1.11 T of memory and 160 CPUs, so it should be able to run as there is nothing else running. How can I fix this?

Thanks in advance,

Jenny

**Comment by jakobnissen** [comment]
Not an IQ-TREE developer, but it looks like the logfile says that IQ-TREE requires 44 GB _per core_, meaning it needs 7 TB RAM for your 160 cores. The `std::bad_alloc` also suggests it's running out of memory.

**Comment by cgy0627** [comment]
Oh ok, that makes sense! Thanks so much, really appreciate it!

Jenny
