### ISSUE TITLE
Output timetree is erroneously ultrametric

### ISSUE THREAD

**Issue by vikram1996** [Cibiv/IQ-TREE#251]
Hello developers,
Running IQ-TREE version 2.2.2.6 (Windows 11 architecture) on an input alignment FASTA file (mafft_output.fasta) and date information (dates.txt) (both attached) results in a perfectly ultrametric tree which is unusual given that the sequences dates are quite different.

The command that produced this result is -
`iqtree-2.2.2.6-Windows\bin\iqtree2.exe -s mafft_output.fasta --date dates.txt --date-ci 100 -m GTR+I+G -asr -B 1000 -alrt 1000 -blmin 1e-9`

Any help on why IQ-TREE produces this unusual output would be appreciated !

All input and  output files for your reference : 
[iqtree on mafft output.zip](https://github.com/Cibiv/IQ-TREE/files/12801903/iqtree.on.mafft.output.zip)

Thank you in advance
Vikram
 @niemasd

**Comment by niemasd** [comment]
Wait, @vikram1996, I don't think this tree is actually ultrametric anymore now that you've run the command line version:

```bash
# we have 6 unique dates
$ cat dates.txt | cut -d' ' -f2 | sort | uniq | wc -l
6

# we have 12 unique root-to-tip distances
$ nw_distance -mr -sf mafft_output.fasta.timetree.nwk | sort | uniq | sed '/^[[:space:]]*$/d' | wc -l
12
```

**Comment by vikram1996** [comment]
Noted - Issue is now closed
