### ISSUE TITLE
Consistent name mangling between tree reading and alignment reading

### ISSUE THREAD

**Issue by MichaelWoodhams** [Cibiv/IQ-TREE#31]
(This is low priority as there is an obvious workaround.)

I downloaded an alignment and tree from TreeBase. Annoyingly, some of
the taxon names contain spaces, and use quotes around them. IQtree reads
the alignment OK, doing some auto-substitutions to deal with space and
quote characters. The problem is then when it reads the tree file, it
doesn't do the same auto-substitutions, so it can't reconcile the
alignment taxa with the tree taxa.

./iqtree -s M39346.fasta -te T100530.treefile -redo -m 012345

**Comment by bqminh** [comment]
solved in v1.6.5
