### ISSUE TITLE
Label empirical state frequencies in partitioned data

### ISSUE THREAD

**Issue by MichaelWoodhams** [Cibiv/IQ-TREE#36]
This is a small cosmetic enhancement request.

My command line:
./iqtree -s peabacteria.nex -te peabacteria.tree -sp partition.nex -redo -pre temp -m 010010+FO -v

Contents of partition.nex:
#nexus
begin sets;
    charset pos1 = 2-1100\3;
    charset pos2 = 3-1100\3;
    charset pos3 = 1-1100\3;
end;

(This alignment did not start on codon partition 1.)
In the output:
Empirical state frequencies: 0.2290836658 0.2372652251 0.4254410892 0.1082100200 
Empirical state frequencies: 0.2776395303 0.2408105227 0.1847849282 0.2967650188 
Empirical state frequencies: 0.0844789551 0.4743215279 0.2938955756 0.1473039413 

Please could you label which partition each of these state frequency vectors belongs to? (As it turns out, they are in order (pos1, pos2, pos3) which makes sense, but later when model fitting it does things in order (pos3, pos1, pos2). )

**Comment by bqminh** [comment]
Let's close this issue, it only concerns -v option which is hardly used
