### ISSUE TITLE
Rare failure of optimization for time reversible models

### ISSUE THREAD

**Issue by MichaelWoodhams** [Cibiv/IQ-TREE#37]
[cormorants.nex.txt](https://github.com/Cibiv/IQ-TREE/files/1534928/cormorants.nex.txt)
[cormorants.tree.txt](https://github.com/Cibiv/IQ-TREE/files/1534929/cormorants.tree.txt)

I have several cases where optimization fails for a time reversible
model. In all cases, the model is 011110+FQ (plus some
rates-across-sites option.) Here is an example:

./iqtree -s cormorants.nex -te cormorants.tree -redo -pre temp -m
011110+FQ+I

[...]

99. Current log-likelihood: -7012.165
Optimal log-likelihood: -7012.165
Rate parameters:  A-C: 1.000  A-G: 89.073  A-T: 89.073  C-G: 89.073
C-T: 89.073  G-T: 1.000
Base frequencies:   A: 0.250  C: 0.250  G: 0.250  T: 0.250
Proportion of invariable sites: 0.616
Parameters optimization took 99 rounds (14.088 sec)
BEST SCORE FOUND : -7012.165

(Sorry, I tried to attach the input files for the example but couldn't make it work. I've e-mailed them to Minh, or you can request them from me.)

Note that this model is like K2P, except with a different pair of rates
being allowed to differ. (K2P would be 010010.)

The problem appears to be that the variable rate parameter leaps to near
100 on the very first iteration, and then only very slowly declines on
further iterations, until iqtree reaches a hard coded maximum of 99
iterations and gives up before converging on the optimum. I suspect the
fix is to look at that very first iteration and place some limit on how
large a leap it can make. I think  it starts with rate A-C: 1.000, rate
A-G:1.000 ('-v' doesn't show this) and next step has A-G: 99.9191431513
(this is the first value shown by '-v'.) If you said "from 1 to 100 in
one go is too far, I'll never change by more than a factor of 3 in a
single step" I think the problem would be solved.

Having said all this, it is a pretty rare problem. I've been doing tests
with 72 time reversible models on about 15 data sets, and I've seen this
I think just three times, all on the 011110+FQ model.

By comparison:

./iqtree -s cormorants.nex -te cormorants.tree -redo -pre temp -m
'011110{20}+FQ+I' -optfromgiven

[...]

11. Current log-likelihood: -6969.449
Optimal log-likelihood: -6969.444
Rate parameters:  A-C: 1.000  A-G: 5.709  A-T: 5.709  C-G: 5.709 C-T:
5.709  G-T: 1.000
Base frequencies:   A: 0.250  C: 0.250  G: 0.250  T: 0.250
Proportion of invariable sites: 0.610
Parameters optimization took 11 rounds (2.306 sec)
BEST SCORE FOUND : -6969.444

This is also a Lie-Markov model, so the following is equivalent (but
uses a different parameterization of the model):

./iqtree -s cormorants.nex -te cormorants.tree -redo -pre temp -m MK2.2b+I

[...]

7. Current log-likelihood: -6969.448
Optimal log-likelihood: -6969.444
Model parameters: -0.759
Substitution rates:
 A-C: 0.241  A-G: 1.379  A-T: 1.379  C-A: 0.241  C-G: 1.379  C-T: 1.379
 G-A: 1.379  G-C: 1.379  G-T: 0.241  T-A: 1.379  T-C: 1.379  T-G: 0.241
Base frequencies:   A: 0.250  C: 0.250  G: 0.250  T: 0.250
Proportion of invariable sites: 0.610
Parameters optimization took 7 rounds (1.617 sec)
BEST SCORE FOUND : -6969.444

**Comment by bqminh** [comment]
DONE! A more robust optimization is now implemented in v1.6.

First the BFGS routine (numerical recipes) is applied as usual. If the estimates are around the boundary, then another routine L-BFGS-B will be invoked starting from the original parameter values. If L-BFGS-B found better log-likelihood, estimates will be updated accordingly. The screen output looks like this:

1. Initial log-likelihood: -7286.219
NICE: L-BFGS-B found better parameters with LnL=-7123.367 than BFGS LnL=-7200.063
2. Current log-likelihood: -6984.429
3. Current log-likelihood: -6971.519
4. Current log-likelihood: -6969.862
5. Current log-likelihood: -6969.536
6. Current log-likelihood: -6969.464
7. Current log-likelihood: -6969.448
Optimal log-likelihood: -6969.444
Rate parameters:  A-C: 1.00000  A-G: 5.71580  A-T: 5.71580  C-G: 5.71580  C-T: 5.71580  G-T: 1.00000
Base frequencies:  A: 0.250  C: 0.250  G: 0.250  T: 0.250
Proportion of invariable sites: 0.610
Parameters optimization took 7 rounds (0.051 sec)
BEST SCORE FOUND : -6969.444
