### ISSUE TITLE
-optfromgiven option does not optimize site proportions in +R models

### ISSUE THREAD

**Issue by MichaelWoodhams** [Cibiv/IQ-TREE#39]
This is related to #38, as I found it when attempting to work around that problem.
The command:
$ ./iqtree -s humanMito.fasta -te humanMito.tree -m 'K3P+R{0.35,0.00001,0.35,0.0001,0.25,1.2,0.05,27}' -pre temp -redo -v -optfromgiven
should optimize the +R parameters, starting at the values specified on the command line. However, it optimizes the rates but not the proportions, in this case finishing at:

Rate parameters:  A-C: 1.0000000000  A-G: 27.6510651518  A-T: 0.9658284715  C-G: 0.9658284715  C-T: 27.6510651518  G-T: 1.0000000000
Base frequencies:   A: 0.2500000000  C: 0.2500000000  G: 0.2500000000  T: 0.2500000000
Site proportion and rates:  (0.3500000000,0.0000060605) (0.3500000000,0.0000606046) (0.2500000000,0.7272557580) (0.0500000000,16.3632545544)
Optimal log-likelihood: -29971.6783480812

As I'm the person who added the -optfromgiven command line option, if I find the time I'll look into this one myself, but I'm logging it here so it doesn't get lost if I forget or don't get around to it.

**Comment by bqminh** [comment]
Done
