### ISSUE TITLE
Heterotachy model base frequency crash

### ISSUE THREAD

**Issue by crotty** [Cibiv/IQ-TREE#46]
On some rare occasions IQ-TREE crashes when running the heterotachy model. Somehow the base frequency vector seems to go to a boundary condition, whereby one base has frequency equal to 1. I suspect the reason is that the upper and lower bounds (1 and 0.0001) on base frequencies are such that it is possible for the sum of fA+fC+fG > 1 as in the example below. The frequency of T is constrained to 1 - (fA+fC+fG) and therefore we have fT < 0 which results in the crash. If this is the cause then a possible solution would be to reduce the upper bound on the base frequencies from 1 down to 0.9997. 

[taxa4_modJC_1kbp_class1Weight0.2_divQ3_fitHKY_H4.log](https://github.com/Cibiv/IQ-TREE/files/1501902/taxa4_modJC_1kbp_class1Weight0.2_divQ3_fitHKY_H4.log)

[taxa4_modJC_1kbp_class1Weight0.2_divQ3.txt](https://github.com/Cibiv/IQ-TREE/files/1501913/taxa4_modJC_1kbp_class1Weight0.2_divQ3.txt)

**Comment by bqminh** [comment]
@crotty: Please test version 1.6.rc, it may have been fixed there.

Thanks, Minh
