### ISSUE TITLE
Implement transfer bootstrap expectation (TBE)

### ISSUE THREAD

**Issue by bqminh** [Cibiv/IQ-TREE#47]
https://doi.org/10.1101/154542

Pers. comm. with Frederic Lemoine and Olivier Gascuel:

we have been working on a new way of computing branch supports, given a reference tree and a set of bootstrap trees. 

The idea is to find, for each branch of the reference tree, the branch of each bootstrap tree that minimizes the taxa "transfer distance". The support of a ref branch will then be computed as 1-(the average distance over bootstrap trees)/(p-1). p being the number of taxa on the light side of this ref branch.

If you are interested and if you want more information, a preprint is available here: 
https://doi.org/10.1101/154542

The paper is otherwise under revision and should hopefully be out in the near future. 

We were wondering if you think it could be interesting to integrate this new support computation in IQ-TREE?
As it is a different way of comparing reference branches to bootstrap trees, it is compatible with all methods that generate a set of bootstrap trees (classical bootstrap as well as Ultra-Fast bootstrap).

We have a C implementation of this computation here: 
https://github.com/evolbioinfo/booster

**Comment by xvazquezc** [comment]
Any update on this?
The paper is out in Nature
https://www.nature.com/articles/s41586-018-0043-0

**Comment by bqminh** [comment]
DONE now in latest branch!
