### ISSUE TITLE
IQ-TREE 1.6.1 crashes with -nt > 1 & -nt AUTO on diverse Ubuntu 16.04 LTS boxes

### ISSUE THREAD

**Issue by vinuesa** [Cibiv/IQ-TREE#52]
Hi Bui, congrats for the great work and the recognition by the SMBE!!! 

# 1. I've been testing IQ-TREE 1.6.1 (pre-compiled 64-bit version for Linus) on my Ubuntu 16.04 desktop box and servers and found that in all of them the program crashes when -nt > 1 or when -nt AUTO. This happens even with the simplest of the commands:

$ iqtree -s regions.fst -st DNA -m HKY+ASC+G -nt AUTO  -redo
IQ-TREE multicore version 1.6.1 for Linux 64-bit built Dec 26 2017
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.

Host:    Tenerife (SSE4.1, 7 GB RAM)
Command: iqtree -s regions.fst -st DNA -m HKY+ASC+G -nt AUTO -redo
Seed:    714051 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Wed Dec 27 19:21:21 2017
Kernel:  SSE2 - auto-detect threads (4 CPU cores detected)

Reading alignment file regions.fst ... Fasta format detected
Alignment most likely contains DNA/RNA sequences
Alignment has 118 sequences with 1195 columns, 1097 distinct patterns
1037 parsimony-informative, 158 singleton sites, 0 constant sites
     Gap/Ambiguity  Composition  p-value
   1  1      0.00%    passed     94.87%
...

NOTE: 111 is identical to 101 but kept for subsequent analysis
NOTE: 115 is identical to 113 but kept for subsequent analysis

Create initial parsimony tree by phylogenetic likelihood library (PLL)... 0.036 seconds
Ascertainment bias correction: 4 unobservable constant patterns

NOTE: 16 MB RAM (0 GB) is required!
Measuring multi-threading efficiency up to 4 CPU cores
Increase to 10 rounds for branch lengths
5 trees examined
Threads: 1 / Time: 4.043 sec / Speedup: 1.000 / Efficiency: 100% / LogL: -65164
*** Error in `iqtree': munmap_chunk(): invalid pointer: 0x00000000015c5110 ***
======= Backtrace: =========
[0x94c911]
[0x958fd2]
[0x5e0ba8]
[0x5a8d16]
[0x439f4c]
[0x445713]
[0x41a9d0]
[0x915f26]
[0x91611a]
[0x402b99]
======= Memory map: ========
00400000-00b57000 r-xp 00000000 08:07 1180657                            /usr/local/biotools/bin/iqtree
00d56000-00d6e000 rw-p 00756000 08:07 1180657                            /usr/local/biotools/bin/iqtree
00d6e000-00d86000 rw-p 00000000 00:00 0 
01211000-02713000 rw-p 00000000 00:00 0                                  [heap]
7fd1b0000000-7fd1b0021000 rw-p 00000000 00:00 0 
7fd1b0021000-7fd1b4000000 ---p 00000000 00:00 0 
7fd1b7bff000-7fd1b7c00000 ---p 00000000 00:00 0 
7fd1b7c00000-7fd1b8000000 rw-p 00000000 00:00 0 
7fd1b8000000-7fd1b8021000 rw-p 00000000 00:00 0 
7fd1b8021000-7fd1bc000000 ---p 00000000 00:00 0 
7fd1bd2ef000-7fd1bd2f0000 rw-p 00000000 00:00 0 
7fd1bd2f0000-7fd1bd2f1000 ---p 00000000 00:00 0 
7fd1bd2f1000-7fd1bd6f1000 rw-p 00000000 00:00 0 
7ffc2577e000-7ffc257a0000 rw-p 00000000 00:00 0                          [stack]
7ffc257bf000-7ffc257c1000 r--p 00000000 00:00 0                          [vvar]
7ffc257c1000-7ffc257c3000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: regions.fst.log
ERROR: ***    Alignment files (if possible)
Aborted (core dumped)

# 2. with -nt 1 it runs smoothly

Host:    Tenerife (SSE4.1, 7 GB RAM)
Command: iqtree -s regions.fst -st DNA -m HKY+G -nt 1 -redo
Seed:    505627 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Wed Dec 27 19:23:34 2017
Kernel:  SSE2 - 1 threads (4 CPU cores detected)

HINT: Use -nt option to specify number of threads because your CPU has 4 cores!
HINT: -nt AUTO will automatically determine the best number of threads to use.

Reading alignment file regions.fst ... Fasta format detected
...

# 3. Also finishes without problems with iqtree-omp 1.5.6

IQ-TREE multicore version 1.5.6 for Linux 64-bit built Dec  4 2017
Copyright (c) 2011-2017 by Bui Quang Minh, Nguyen Lam Tung,
Olga Chernomor, Heiko Schmidt, and Arndt von Haeseler.

Host:    Tenerife (SSE4.1, 7 GB RAM)
Command: /home/vinuesa/Software_downloads/iqtree-omp-1.5.6-Linux/bin/iqtree-omp -s regions.fst -st DNA -m HKY+G -nt AUTO -redo
Seed:    977243 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Wed Dec 27 19:28:02 2017
Kernel:  SSE2 - auto-detect threads (4 CPU cores detected)

Reading alignment file regions.fst ... Fasta format detected
Alignment most likely contains DNA/RNA sequences
Alignment has 118 sequences with 1195 columns and 1097 patterns (1037 informative sites, 0 constant sites)
...
__END__

Would be great to get your feedback on this issue!
Keep up with the great work!
Cheers,
Pablo

**Comment by bqminh** [comment]
Hi @vinuesa, thanks for testing the new version.

For debugging purpose, can you please send me the data via personal email? Or if it's not confidential, post it here. 

Minh

**Comment by vinuesa** [comment]
Hi @bqminh, many thanks for your prompt reply! Please find enclosed the alignment.
[regions.fst.gz](https://github.com/Cibiv/IQ-TREE/files/1591687/regions.fst.gz)

Best,
Pablo

**Comment by bqminh** [comment]
Many thanks! I found and fixed the problem. It was introduced in the previous commit and not present in 1.6.0. Please test it again: https://github.com/Cibiv/IQ-TREE/releases/tag/v1.6.1
Minh

**Comment by vinuesa** [comment]
Hey Bui, many thanks for the VERY fast reply and bug fix. All tests run perfectly well now. You're great!
I'll let you know , should I find any further issues.
Best,
Pablo
