### ISSUE TITLE
Setting maximum number of CPUs with AUTO

### ISSUE THREAD

**Issue by sjspielman** [Cibiv/IQ-TREE#57]
Hi, 

I am looking to run iqtree on a cluster and would like to be able to take advantage of `-nt AUTO`. However, by default, iqtree is detecting the total number of cores on the given compute node, which may or may not match the resource allocation requested. For example, if a node has 64 cores but my job only requested 32, I would like to be able to use AUTO while also specifying "no more than 32". Is this possible with the current version?

Thanks!
-Stephanie

**Comment by bqminh** [comment]
Hi Stephanie, this is a reasonable request, right now there is no option to restrict the max number of cores when doing -nt AUTO. But that should be easy to implement, e.g. with a new -ntmax option.

Minh

**Comment by jvollme** [comment]
I was just about to post the same Issue when I noticed it was posted here already.
This would be a very important feature for safe usage of iqtree on shared clusters. Really hope that you can implement it in the next release...

**Comment by bqminh** [comment]
Can you please test beta version /releases/v1.6.2.a ?

 It has a new option, for example, -ntmax 10 to restrict the maximum of 10 CPU cores.

**Comment by sjspielman** [comment]
Hi Minh, 

Tested Mac and Linux versions, works as expected! Thanks!

-Stephanie

**Comment by RaSieb** [comment]
Is this an issue only here locally, or do others also experience that the `-ntmax / --max-threads`  option is ignored in iqtree? I have tested both with iqtree 2.1.2 and 1.6.9 (which is wrongly stated as 1-6-12 in the attached screenshot), and under the `Creating fast initial parsimony tree by random order stepwise addition...` step, all CPU's of the node are taken when using "AUTO". [edit] I have to note that this was ran with 12k COVID-19 sequences. It seems like there is no issue with around 8k sequences...
![Screen Shot 2021-01-14 at 11 42 52](https://user-images.githubusercontent.com/19334536/104581030-4d603f80-565e-11eb-8aec-3796df0aad2a.png)

**Comment by bqminh** [comment]
Hi there, please see an answer and solution here:

https://github.com/iqtree/iqtree2/issues/18 <https://github.com/iqtree/iqtree2/issues/18>
