### ISSUE TITLE
Feature request: argument to specify output prefix

### ISSUE THREAD

**Issue by jvollme** [Cibiv/IQ-TREE#58]
Currently iqtree creates output files based on the name of the input file.
Sometimes, however, it would be nice to run & compare several runs of iqtree at the same time, using the same input data but playing around with the exact parameters.
But that would require some more control on how the output (and the indermediate results & checkpoints)  will be named, in order to avoid conflicts between the parallel runs. Would it be possible to add such an option? Or does this option already exist (and I simply missed it in the documentation)?

**Comment by bqminh** [comment]
There is already an option -pre for setting prefix of all output files:

http://www.iqtree.org/doc/Tutorial#first-running-example <http://www.iqtree.org/doc/Tutorial#first-running-example>

Minh

**Comment by jvollme** [comment]
oh right, sorry
