### ISSUE TITLE
+G with user-defined protein model

### ISSUE THREAD

**Issue by sjspielman** [Cibiv/IQ-TREE#59]
Hi IQ-Tree team, 

Is it possible to specify a gamma distribution for rate heterogeneity in conjunction with a user-supplied protein model? Since the model in this case is the filename containing the PAML model, it's not clear to me whether this is possible to specify. If not available currently, it would be a great feature to include for developing and testing new amino acid models.

Thanks, 
Stephanie

**Comment by bqminh** [comment]
Yes you can. Simply do -m PROTEIN_MODEL_FILENAME+G.

**Comment by sjspielman** [comment]
Excellent, thank you!
