### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by linsson** [Cibiv/IQ-TREE#60]
Hi!

I am trying to compile iqtree v 1.6.2 from sources but I get the following error:

-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/local/gcc/4.8.3/gcc/bin/gcc
-- Check for working C compiler: /usr/local/gcc/4.8.3/gcc/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/local/gcc/4.8.3/gcc/bin/g++
-- Check for working CXX compiler: /usr/local/gcc/4.8.3/gcc/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
IQ-TREE flags : 
Builde mode   : Release
Target OS     : Unix
Compiler      : GNU Compiler (gcc)
Target binary : 64-bit
OpenMP        : Yes
MPI           : NONE
Vectorization : SSE3/AVX/AVX2
C flags       :  -fPIC -O2 -pipe -march=native -mtune=native    -I/usr/local/gcc/4.8.3//eigen/3.3.4/include    -pthread  -O3 -g -ffunction-sections -fdata-sections
CXX flags     :  -fPIC -O2 -pipe -march=native -mtune=native    -I/usr/local/gcc/4.8.3//eigen/3.3.4/include    -std=c++11 -fopenmp -pthread  -O3 -g -ffunction-sections -fdata-sections
LINKER flags  :     -rdynamic  -Wl,--gc-sections
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for getrusage
-- Looking for getrusage - found
-- Looking for GlobalMemoryStatusEx
-- Looking for GlobalMemoryStatusEx - not found
-- Looking for strndup
-- Looking for strndup - found
CMake Warning at CMakeLists.txt:438 (find_package):
  By not providing "FindBacktrace.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Backtrace", but CMake did not find one.

  Could not find a package configuration file provided by "Backtrace" with
  any of the following names:

    BacktraceConfig.cmake
    backtrace-config.cmake

  Add the installation prefix of "Backtrace" to CMAKE_PREFIX_PATH or set
  "Backtrace_DIR" to a directory containing one of the above files.  If
  "Backtrace" provides a separate development package or SDK, be sure it has
  been installed.

-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
Using system zlib
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/software_scientifico/IQ-TREE-1.6.2/build
Scanning dependencies of target kernelfma
[  0%] Building CXX object CMakeFiles/kernelfma.dir/tree/phylokernelfma.cpp.o
In file included from /usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectorclass.h:41:0,
                 from /usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectormath_common.h:35,
                 from /usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectormath_exp.h:38,
                 from /usr/local/src/software_scientifico/IQ-TREE-1.6.2/tree/phylokernelfma.cpp:9:
/usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectori128.h: In function ‘Vec8sb operator>(const Vec8us&, const Vec8us&)’:
/usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectori128.h:1794:38: error: could not convert ‘Vec8s((* & _mm_comgt_epu16((& a)->Vec8us::<anonymous>.Vec8s::operator __m128i(), (& b)->Vec8us::<anonymous>.Vec8s::operator __m128i())))’ from ‘Vec8s’ to ‘Vec8sb’
     return (Vec8s)_mm_comgt_epu16(a,b);
                                      ^
make[2]: *** [CMakeFiles/kernelfma.dir/tree/phylokernelfma.cpp.o] Error 1
make[1]: *** [CMakeFiles/kernelfma.dir/all] Error 2
make: *** [all] Error 2

Any clue, please?

**Comment by bqminh** [comment]
There was an error that FindBacktrace.cmake was not found. Can you please install this or copy this file to the source code folder and compile again?

**Comment by linsson** [comment]
Hi, thanks for your answer. I thought the missing backtrace was only a warning, not an error. The error seems to be in the conversion ‘Vec8s’ to ‘Vec8sb’. Anyway, I am not sure I understand how to install backtrace. I tried to locate it:

locate backtrace
/boot/grub/i386-pc/backtrace.mod
/usr/lib/gcc/x86_64-linux-gnu/4.8/libbacktrace.a
/usr/lib/gcc/x86_64-linux-gnu/4.8/32/libbacktrace.a
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/backtrace-supported.h
/usr/lib/gcc/x86_64-linux-gnu/4.8/include/backtrace.h
/usr/lib/gcc/x86_64-linux-gnu/4.8/x32/libbacktrace.a
/usr/lib/grub/i386-pc/backtrace.mod
/usr/share/man/man3/backtrace.3.gz
/usr/share/man/man3/backtrace_symbols.3.gz
/usr/share/man/man3/backtrace_symbols_fd.3.gz
/usr/src/linux-headers-3.13.0-107/arch/tile/include/asm/backtrace.h
/usr/src/linux-headers-3.13.0-135/arch/tile/include/asm/backtrace.h
/usr/src/linux-headers-3.13.0-139/arch/tile/include/asm/backtrace.h
/usr/src/linux-headers-3.13.0-24/arch/tile/include/asm/backtrace.h

I guess it should be installed. Maybe I missed to make CMAKE aware of it when building it. Do you mean that? In case, please, how do you build a backtrace-aware CMAKE?  

Best

**Comment by bqminh** [comment]
Can you copy FindBacktrace.cmake
https://github.com/Kitware/CMake/blob/master/Modules/FindBacktrace.cmake
To IQ-TREE source code folder and run cmake again?
If still not work, please upgrade to gcc5.
Let me know how it goes.

**Comment by linsson** [comment]
Hi and thanks for your reply. I am trying with:

`cd IQ-TREE-${IQTREE_VERSION} && \
  wget --no-check-certificate https://github.com/Kitware/CMake/blob/master/Modules/FindBacktrace.cmake && \
  mkdir build && cp FindBacktrace.cmake build && cd build && cmake .. -DEIGEN3_INCLUDE_DIR=${GLOBAL_PREFIX}/eigen/${EIGEN_VERSION}/include && \
  make`

but I get:

`--2018-04-09 18:22:52--  https://github.com/Kitware/CMake/blob/master/Modules/FindBacktrace.cmake
Resolving github.com... 192.30.253.113, 192.30.253.112
Connecting to github.com|192.30.253.113|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: “FindBacktrace.cmake”

     0K .......... .......... .......... .......... ..........  218K
    50K .......... .......... .......... .......... ..........  436K
   100K .......... .......                                     36.3M=0.3s

2018-04-09 18:22:54 (340 KB/s) - “FindBacktrace.cmake” saved [119856]

-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /gporq1_256k/store_0/usr/aprea/software/cresco4/gcc/4.8.3/gcc/bin/gcc
-- Check for working C compiler: /gporq1_256k/store_0/usr/aprea/software/cresco4/gcc/4.8.3/gcc/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /gporq1_256k/store_0/usr/aprea/software/cresco4/gcc/4.8.3/gcc/bin/g++
-- Check for working CXX compiler: /gporq1_256k/store_0/usr/aprea/software/cresco4/gcc/4.8.3/gcc/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
IQ-TREE flags : 
Builde mode   : Release
Target OS     : Unix
Compiler      : GNU Compiler (gcc)
Target binary : 64-bit
OpenMP        : Yes
MPI           : NONE
Vectorization : SSE3/AVX/AVX2
C flags       : -fPIC -O2 -pipe -march=native -mtune=native    -I/gporq1_256k/store_0/usr/aprea/software/cresco4/gcc/4.8.3//eigen/3.3.4/include -pthread  -O3 -g -ffunction-sections -fdata-sections
CXX flags     : -fPIC -O2 -pipe -march=native -mtune=native    -I/gporq1_256k/store_0/usr/aprea/software/cresco4/gcc/4.8.3//eigen/3.3.4/include -std=c++11 -fopenmp -pthread  -O3 -g -ffunction-sections -fdata-sections
LINKER flags  :  -rdynamic  -Wl,--gc-sections
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for getrusage
-- Looking for getrusage - found
-- Looking for GlobalMemoryStatusEx
-- Looking for GlobalMemoryStatusEx - not found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /usr/include  
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.3") 
Using system zlib
-- Configuring done
-- Generating done
-- Build files have been written to: /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/build
Scanning dependencies of target kernelsse
[  0%] Building CXX object CMakeFiles/kernelsse.dir/tree/phylokernelsse.cpp.o
/gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/tree/phylokernelsse.cpp:157:1: error: ‘__m128d selectd(const __m128d&, const __m128d&, const __m128d&)’ conflicts with a previous declaration
 }
 ^
In file included from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectorclass.h:51:0,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectormath_common.h:35,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectormath_exp.h:38,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/tree/phylokernelsse.cpp:9:
/gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectorf256.h:69:23: note: previous declaration ‘__m256d selectd(const __m256d&, const __m256d&, const __m256d&)’
 static inline __m256d selectd (__m256d const & s, __m256d const & a, __m256d const & b) {
                       ^
In file included from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectorclass.h:42:0,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectormath_common.h:35,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectormath_exp.h:38,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/tree/phylokernelsse.cpp:9:
/gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectorf128.h:79:23: note: -fabi-version=6 (or =0) avoids this error with a change in mangling
 static inline __m128d selectd (__m128d const & s, __m128d const & a, __m128d const & b) {
                       ^
/gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/tree/phylokernelsse.cpp:157:1: error: ‘__m128 selectf(const __m128&, const __m128&, const __m128&)’ conflicts with a previous declaration
 }
 ^
In file included from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectorclass.h:51:0,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectormath_common.h:35,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectormath_exp.h:38,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/tree/phylokernelsse.cpp:9:
/gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectorf256.h:60:22: note: previous declaration ‘__m256 selectf(const __m256&, const __m256&, const __m256&)’
 static inline __m256 selectf (__m256 const & s, __m256 const & a, __m256 const & b) {
                      ^
In file included from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectorclass.h:42:0,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectormath_common.h:35,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectormath_exp.h:38,
                 from /gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/tree/phylokernelsse.cpp:9:
/gporq1_256k/store_0/usr/aprea/software/cresco4/src/IQ-TREE-1.6.2/vectorclass/vectorf128.h:62:22: note: -fabi-version=6 (or =0) avoids this error with a change in mangling
 static inline __m128 selectf (__m128 const & s, __m128 const & a, __m128 const & b) {
                      ^
make[2]: *** [CMakeFiles/kernelsse.dir/tree/phylokernelsse.cpp.o] Error 1
make[1]: *** [CMakeFiles/kernelsse.dir/all] Error 2
make: *** [all] Error 2
`

Actually I do not understand your suggestion. I only had a warning about FindBacktrace.cmake while the error looks about vectorclass. Unfortunately upgrading to gcc5 is not so easy at the moment...

**Comment by bqminh** [comment]
It could be an issue with gcc 4.8 only. Can you upgrade gcc to version 5 or more?

**Comment by bqminh** [comment]
Assume fixed
