### ISSUE TITLE
Custom mixture profiles

### ISSUE THREAD

**Issue by dschrempf** [Cibiv/IQ-TREE#66]
Hi Minh,

I am trying to run IQ-TREE with custom mixture profiles (maybe see also #65). The command line is

    iqtree -nt 4 -s A00000.1y77.ALL_GB.NoIdt -mdef clusters_08_lclr_iqtree.nex -m "GTR20+CF08Model+G" -redo -mwopt

However, the frequency mixture weights are not estimated (but set to 1/8 in this case). Also, the frequency mixtures are not the ones specified in the model file, but are the empirical ones. Effectively, this is running a model with eight equal, empirical frequency profiles.

Maybe I am not correctly specifying the frequency mixture model?

Thanks,
Dominik

[IQ-TREE.tar.gz](https://github.com/Cibiv/IQ-TREE/files/1886327/IQ-TREE.tar.gz)

**Comment by bqminh** [comment]
I just fixed this bug, see commit 216069a3e6 in the latest branch. It is just one line of code!
Minh

**Comment by bqminh** [comment]
Fixed in v1.6.3.b
