### ISSUE TITLE
Document computing a likelihood only, and perhaps allow a single flag for it.

### ISSUE THREAD

**Issue by bredelings** [Cibiv/IQ-TREE#67]
Hi,

Given the number of models that IQ-TREE implements, some users may be interested in computing a likelihood only, with no following optimization.

1. It might be worth documenting that the following options seem to work:
'-keep-ident','-blfix','-vvv','-redo','-blmin','0.0000000000000001'

* -vvv: increases the number of digits of precision for the _initial_ likelihood.
* -redo: over-write any previous analysis, which might bother some users who also sometimes do optimization.

2. In addtion, a "--show-likelihood" or similarly-named option would be a nice bonus for the class of users who (at the moment) just want a likelihood and do not need optimization.  Other users might benefit if this option ignores current output files, instead of over-writing them.

I will mark this as an enhancement, since it probably does not concern the majority of users.

**Comment by bredelings** [comment]
I guess I should maybe also add `-n 0`?

**Comment by MichaelWoodhams** [comment]
From the command line help output:
      Models can have parameters appended in brackets.
           e.g. '-mRY3.4{0.2,-0.3}+I' specifies parameters for
           RY3.4 model but leaves proportion of invariant sites
           unspecified. '-mRY3.4{0.2,-0.3}+I{0.5} gives both.
           When this is done, the given parameters will be taken
           as fixed (default) or as start point for optimization
           (if -optfromgiven option supplied)

So if you specify a model with parameters and do not also specify -optfromgiven, it will use those model parameters as fixed, and not optimize them. I implemented this for some work using DNA models, it has not been tested (at least not by me) on amino acid models, mixture models etc. Also note '-te' option which avoids tree topology optimization, and -blfix which avoids branch length optimization. -te, -blfix and specified model parameters in combination should lead to no optimization occurring.


________________________________

**Comment by bqminh** [comment]
Done in v1.6.7.1 with option `--show-lh`
