### ISSUE TITLE
IQTREE fails on new architecture

### ISSUE THREAD

**Issue by sjspielman** [Cibiv/IQ-TREE#70]
Hi iqtree team, 

My lab group has recently updated our computing cluster with new processors AMD EPYC 7401 on Linux kernel 3.10.0, with the gcc-7 compiler.

I am finding that iqtree (v1.6.2, but I've experienced with 1.6.5 as well)

 produces consistent errors for partitioned analyses on these new nodes, with and without -safe mode turned on. The errors vary depending on the dataset. 

I've attached an example alignment (note I had to add extension .txt to the fasta file to get to to attach here) and output files, with errors indicated. Thanks!

Best, 
Stephanie

Input: 
+ [temp.fasta.txt](https://github.com/Cibiv/IQ-TREE/files/2069383/temp.fasta.txt)
+ [temp_partitions.txt](https://github.com/Cibiv/IQ-TREE/files/2069381/temp_partitions.txt)

Output:
+ [temp_partitions.txt.log](https://github.com/Cibiv/IQ-TREE/files/2069380/temp_partitions.txt.log)
+ [temp_partitions.txt.treefile.txt](https://github.com/Cibiv/IQ-TREE/files/2069382/temp_partitions.txt.treefile.txt)
+ [temp_partitions.txt.ckp.gz](https://github.com/Cibiv/IQ-TREE/files/2069379/temp_partitions.txt.ckp.gz)

**Comment by bqminh** [comment]
I couldn't replicate the crash... IQ-TREE runs smoothly here (Mac OS) on your data set. Not sure what went wrong at your system...
Minh

**Comment by bqminh** [comment]
I assume this was resolved as there is no follow-up from the original poster
