### ISSUE TITLE
During AU test, 1.6.6&1.6.7 crashes with following error, while 1.6.1 is works fine for both my macOS High Sierra and Ubuntu 14.04

### ISSUE THREAD

**Issue by Kinggerm** [Cibiv/IQ-TREE#72]
IQ-TREE multicore version 1.6.6 for Mac OS X 64-bit built Jul  1 2018
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.

Host:    KMBP (AVX2, FMA3, 16 GB RAM)
Command: iqtree -s test.fasta -z no_br.trees -zb 1000 -au -nt 2
Seed:    36129 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Sun Jul 22 16:08:34 2018
Kernel:  AVX+FMA - 2 threads (8 CPU cores detected)

Reading alignment file test.fasta ... Fasta format detected
Alignment most likely contains DNA/RNA sequences
Alignment has 4 sequences with 10 columns, 8 distinct patterns
2 parsimony-informative, 3 singleton sites, 5 constant sites
   Gap/Ambiguity  Composition  p-value
   1  A    0.00%    passed     98.80%
   2  B    0.00%    passed     74.18%
   3  C    0.00%    passed     76.05%
   4  D    0.00%    passed     95.78%
****  TOTAL    0.00%  0 sequences failed composition chi2 test (p-value<5%; df=3)

Create initial parsimony tree by phylogenetic likelihood library (PLL)... 0.002 seconds
NOTE: ModelFinder requires 0 MB RAM!
ModelFinder will test 286 DNA models (sample size: 10) ...
 No. Model         -LnL         df  AIC          AICc         BIC
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
  1  JC            32.615       5   75.230       90.230       76.743
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
  2  JC+I          32.615       6   77.230       105.230      79.045
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
  3  JC+G4         32.616       6   77.231       105.231      79.047
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
  4  JC+I+G4       32.893       7   79.786       135.786      81.904
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
  5  JC+R2         32.628       7   79.256       135.256      81.374
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
  6  JC+R3         32.618       9   83.236       263.236      85.959
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 14  F81+F         32.170       8   80.339       224.339      82.760
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 15  F81+F+I       32.170       9   82.339       262.339      85.063
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 16  F81+F+G4      32.171       9   82.341       262.341      85.064
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 17  F81+F+I+G4    32.411       10  84.821       304.821      87.847
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 18  F81+F+R2      32.171       10  84.343       304.343      87.368
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 19  F81+F+R3      32.170       12  88.340       400.340      91.971
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 27  K2P           30.837       6   73.674       101.674      75.489
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 28  K2P+I         30.837       7   75.674       131.674      77.792
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 29  K2P+G4        30.838       7   75.675       131.675      77.794
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 30  K2P+I+G4      31.037       8   78.074       222.074      80.495
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 31  K2P+R2        30.837       8   77.674       221.674      80.095
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 32  K2P+R3        30.837       10  81.674       301.674      84.700
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 40  HKY+F         30.217       9   78.433       258.433      81.156
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 41  HKY+F+I       30.217       10  80.433       300.433      83.459
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 42  HKY+F+G4      30.218       10  80.435       300.435      83.461
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 43  HKY+F+I+G4    30.405       11  82.810       346.810      86.138
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 44  HKY+F+R2      30.217       11  82.433       346.433      85.762
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 45  HKY+F+R3      30.217       13  86.433       450.433      90.367
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 53  TNe           30.837       7   75.674       131.674      77.792
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 54  TNe+I         30.837       8   77.674       221.674      80.094
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 55  TNe+G4        30.838       8   77.675       221.675      80.096
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 56  TNe+I+G4      30.960       9   79.920       259.920      82.643
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 57  TNe+R2        30.837       9   79.674       259.674      82.397
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 58  TNe+R3        30.837       11  83.674       347.674      87.002
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 66  TN+F          30.217       10  80.433       300.433      83.459
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 67  TN+F+I        30.217       11  82.433       346.433      85.762
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 68  TN+F+G4       30.218       11  82.435       346.435      85.764
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 69  TN+F+I+G4     30.336       12  84.671       396.671      88.302
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 70  TN+F+R2       30.217       12  84.433       396.433      88.064
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 71  TN+F+R3       30.217       14  88.433       508.433      92.669
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 79  K3P           30.756       7   75.512       131.512      77.630
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 80  K3P+I         30.725       8   77.450       221.450      79.871
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 81  K3P+G4        30.726       8   77.452       221.452      79.873
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 82  K3P+I+G4      30.804       9   79.607       259.607      82.331
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 83  K3P+R2        30.725       9   79.450       259.450      82.174
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 84  K3P+R3        30.725       11  83.450       347.450      86.779
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 92  K3Pu+F        30.100       10  80.201       300.201      83.227
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 93  K3Pu+F+I      30.100       11  82.201       346.201      85.529
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 94  K3Pu+F+G4     30.101       11  82.203       346.203      85.531
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 95  K3Pu+F+I+G4   30.179       12  84.357       396.357      87.989
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 96  K3Pu+F+R2     30.100       12  84.201       396.201      87.832
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
 97  K3Pu+F+R3     30.100       14  88.201       508.201      92.437
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
105  TPM2+F        30.127       10  80.254       300.254      83.279
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
106  TPM2+F+I      30.052       11  82.103       346.103      85.432
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
107  TPM2+F+G4     30.053       11  82.105       346.105      85.434
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
108  TPM2+F+I+G4   30.120       12  84.240       396.240      87.871
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
109  TPM2+F+R2     30.052       12  84.103       396.103      87.734
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
110  TPM2+F+R3     30.052       14  88.103       508.103      92.339
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
118  TPM2u+F       30.052       10  80.103       300.103      83.129
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
119  TPM2u+F+I     30.052       11  82.103       346.103      85.432
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
120  TPM2u+F+G4    30.053       11  82.105       346.105      85.434
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
121  TPM2u+F+I+G4  30.104       12  84.208       396.208      87.839
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
122  TPM2u+F+R2    30.052       12  84.103       396.103      87.734
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
123  TPM2u+F+R3    30.052       14  88.103       508.103      92.339
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
131  TPM3+F        30.187       10  80.375       300.375      83.401
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
132  TPM3+F+I      30.186       11  82.371       346.371      85.699
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
133  TPM3+F+G4     30.187       11  82.373       346.373      85.702
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
134  TPM3+F+I+G4   30.222       12  84.444       396.444      88.075
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
135  TPM3+F+R2     30.186       12  84.371       396.371      88.002
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
136  TPM3+F+R3     30.186       14  88.371       508.371      92.607
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
144  TPM3u+F       30.186       10  80.371       300.371      83.397
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
145  TPM3u+F+I     30.186       11  82.371       346.371      85.699
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
146  TPM3u+F+G4    30.187       11  82.373       346.373      85.702
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
147  TPM3u+F+I+G4  30.215       12  84.430       396.430      88.061
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
148  TPM3u+F+R2    30.186       12  84.371       396.371      88.002
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
149  TPM3u+F+R3    30.186       14  88.371       508.371      92.607
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
157  TIMe          30.756       8   77.512       221.512      79.933
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
158  TIMe+I        30.726       9   79.452       259.452      82.175
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
159  TIMe+G4       30.726       9   79.452       259.452      82.175
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
160  TIMe+I+G4     30.745       10  81.490       301.490      84.516
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
161  TIMe+R2       30.725       10  81.450       301.450      84.476
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
162  TIMe+R3       30.725       12  85.450       397.450      89.081
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
170  TIM+F         30.100       11  82.201       346.201      85.529
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
171  TIM+F+I       30.100       12  84.201       396.201      87.832
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
172  TIM+F+G4      30.101       12  84.203       396.203      87.834
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
173  TIM+F+I+G4    30.120       13  86.241       450.241      90.174
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
174  TIM+F+R2      30.100       13  86.201       450.201      90.134
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
175  TIM+F+R3      30.100       15  90.201       570.201      94.739
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
183  TIM2e         30.753       8   77.505       221.505      79.926
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
184  TIM2e+I       30.715       9   79.430       259.430      82.153
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
185  TIM2e+G4      30.715       9   79.430       259.430      82.153
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
186  TIM2e+I+G4    30.729       10  81.457       301.457      84.483
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
187  TIM2e+R2      30.714       10  81.428       301.428      84.454
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
188  TIM2e+R3      30.714       12  85.428       397.428      89.059
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
196  TIM2+F        30.052       11  82.104       346.104      85.433
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
197  TIM2+F+I      30.052       12  84.103       396.103      87.734
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
198  TIM2+F+G4     30.053       12  84.105       396.105      87.736
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
199  TIM2+F+I+G4   30.067       13  86.133       450.133      90.067
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
200  TIM2+F+R2     30.052       13  86.103       450.103      90.037
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
201  TIM2+F+R3     30.052       15  90.103       570.103      94.642
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
209  TIM3e         30.780       8   77.560       221.560      79.980
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
210  TIM3e+I       30.773       9   79.546       259.546      82.269
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
211  TIM3e+G4      30.773       9   79.546       259.546      82.270
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
212  TIM3e+I+G4    30.781       10  81.562       301.562      84.588
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
213  TIM3e+R2      30.772       10  81.545       301.545      84.570
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
214  TIM3e+R3      30.772       12  85.545       397.545      89.176
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
222  TIM3+F        30.186       11  82.371       346.371      85.699
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
223  TIM3+F+I      30.186       12  84.371       396.371      88.002
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
224  TIM3+F+G4     30.187       12  84.373       396.373      88.004
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
225  TIM3+F+I+G4   30.195       13  86.389       450.389      90.323
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
226  TIM3+F+R2     30.186       13  86.371       450.371      90.305
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
227  TIM3+F+R3     30.186       15  90.371       570.371      94.910
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
235  TVMe          30.609       9   79.217       259.217      81.941
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
236  TVMe+I        30.587       10  81.173       301.173      84.199
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
237  TVMe+G4       30.573       10  81.146       301.146      84.172
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
238  TVMe+I+G4     30.578       11  83.156       347.156      86.485
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
239  TVMe+R2       30.571       11  83.143       347.143      86.471
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
240  TVMe+R3       30.571       13  87.143       451.143      91.076
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
248  TVM+F         29.941       12  83.882       395.882      87.513
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
249  TVM+F+I       29.941       13  85.882       449.882      89.816
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
250  TVM+F+G4      29.942       13  85.885       449.885      89.818
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
251  TVM+F+I+G4    29.948       14  87.897       507.897      92.133
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
252  TVM+F+R2      29.941       14  87.882       507.882      92.119
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
253  TVM+F+R3      29.941       16  91.882       635.882      96.724
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
261  SYM           30.571       10  81.143       301.143      84.169
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
262  SYM+I         30.571       11  83.142       347.142      86.471
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
263  SYM+G4        30.572       11  83.144       347.144      86.473
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
264  SYM+I+G4      30.576       12  85.152       397.152      88.783
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
265  SYM+R2        30.571       12  85.142       397.142      88.773
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
266  SYM+R3        30.571       14  89.142       509.142      93.379
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
274  GTR+F         29.941       13  85.883       449.883      89.816
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
275  GTR+F+I       29.941       14  87.882       507.882      92.118
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
276  GTR+F+G4      29.942       14  87.884       507.884      92.121
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
277  GTR+F+I+G4    29.946       15  89.892       569.892      94.431
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
278  GTR+F+R2      29.941       15  89.882       569.882      94.421
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
279  GTR+F+R3      29.941       17  93.882       705.882      99.026
Akaike Information Criterion:           K2P
Corrected Akaike Information Criterion: JC
Bayesian Information Criterion:         K2P
Best-fit model: K2P chosen according to BIC

All model information printed to test.fasta.model.gz
CPU time for ModelFinder: 0.157 seconds (0h:0m:0s)
Wall-clock time for ModelFinder: 0.098 seconds (0h:0m:0s)

NOTE: 0 MB RAM (0 GB) is required!
WARNING: Number of threads seems too high for short alignments. Use -nt AUTO to determine best number of threads.
Estimate model parameters (epsilon = 0.100)
1. Initial log-likelihood: -32.618
2. Current log-likelihood: -30.840
Optimal log-likelihood: -30.837
Rate parameters:  A-C: 1.00000  A-G: 0.00010  A-T: 1.00000  C-G: 1.00000  C-T: 0.00010  G-T: 1.00000
Base frequencies:  A: 0.250  C: 0.250  G: 0.250  T: 0.250
Parameters optimization took 2 rounds (0.001 sec)
Computing ML distances based on estimated model parameters... 0.001 sec
Computing BIONJ tree...
0.000 seconds
Log-likelihood of BIONJ tree: -30.837
--------------------------------------------------------------------
|             INITIALIZING CANDIDATE TREE SET                      |
--------------------------------------------------------------------
Generating 99 parsimony trees... 0.007 second
Computing log-likelihood of 2 initial trees ... 0.000 seconds
Current best score: -30.837

Do NNI search on 3 best initial trees
UPDATE BEST LOG-LIKELIHOOD: -30.837
Finish initializing candidate tree set (3)
Current best tree score: -30.837 / CPU time: 0.009
Number of iterations: 3
--------------------------------------------------------------------
|               OPTIMIZING CANDIDATE TREE SET                      |
--------------------------------------------------------------------
UPDATE BEST LOG-LIKELIHOOD: -30.837
Iteration 10 / LogL: -30.839 / Time: 0h:0m:0s
UPDATE BEST LOG-LIKELIHOOD: -30.837
Iteration 20 / LogL: -30.839 / Time: 0h:0m:0s
Iteration 30 / LogL: -30.837 / Time: 0h:0m:0s (0h:0m:0s left)
Iteration 40 / LogL: -30.837 / Time: 0h:0m:0s (0h:0m:0s left)
Iteration 50 / LogL: -30.837 / Time: 0h:0m:0s (0h:0m:0s left)
Iteration 60 / LogL: -30.837 / Time: 0h:0m:0s (0h:0m:0s left)
Iteration 70 / LogL: -30.839 / Time: 0h:0m:0s (0h:0m:0s left)
Iteration 80 / LogL: -30.839 / Time: 0h:0m:0s (0h:0m:0s left)
Iteration 90 / LogL: -30.837 / Time: 0h:0m:0s (0h:0m:0s left)
Iteration 100 / LogL: -30.837 / Time: 0h:0m:0s (0h:0m:0s left)
TREE SEARCH COMPLETED AFTER 101 ITERATIONS / Time: 0h:0m:0s

--------------------------------------------------------------------
|                    FINALIZING TREE SEARCH                        |
--------------------------------------------------------------------
Performs final model parameters optimization
Estimate model parameters (epsilon = 0.010)
1. Initial log-likelihood: -30.837
Optimal log-likelihood: -30.837
Rate parameters:  A-C: 1.00000  A-G: 0.00010  A-T: 1.00000  C-G: 1.00000  C-T: 0.00010  G-T: 1.00000
Base frequencies:  A: 0.250  C: 0.250  G: 0.250  T: 0.250
Parameters optimization took 1 rounds (0.000 sec)
BEST SCORE FOUND : -30.837
Total tree length: 0.552

Total number of iterations: 101
CPU time used for tree search: 0.069 sec (0h:0m:0s)
Wall-clock time used for tree search: 0.036 sec (0h:0m:0s)
Total CPU time used: 0.084 sec (0h:0m:0s)
Total wall-clock time used: 0.045 sec (0h:0m:0s)

Reading trees in no_br.trees ...
2 trees detected
Note: 0.061 MB of RAM required!
Creating 1000 bootstrap replicates...
done
Tree 1 / LogL: -30.837
Tree 2 / LogL: -34.343
Performing RELL-BP test...
Performing KH and SH test...
Performing ELW test...
Performing approximately unbiased (AU) test...
WARNING: Too few replicates for AU test. At least -zb 10000 for reliable results!
0 MB required for AU test
Generating 10 x 1000 multiscale bootstrap replicates... ERROR: STACK TRACE FOR
ERROR:  DEBUGGIN*G*:* IQ-TRE CRA
ERROR: SHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: test.fasta.log
ERROR: ***    Alignment files (if possible)

Alignment (test.fasta):
>\>A
>ATTGTCCCGA
>\>B
>ATGGTCCCCA
>\>C
>TTTTTACCGA
>\>D
>TTTGTACCGA

Trees (no_br.tre):
>(A,B,(C,D));
>(A,C,(B,D));

**Comment by CarlosSantanaMolina** [comment]
Concernign to AU test bug, thanks for share this info. 
Following the instrucctions in IQ-tree webpage (http://www.iqtree.org/doc/Advanced-Tutorial), I also had problems performing the AU topology-test with next warnings:

"""
WARNING: Too few replicates for AU test. At least -zb 10000 for reliable results!
0 MB required for AU test
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
Generating 10 x 1000 multiscale bootstrap replicates... ERROR: STACK TRACE FOR DEBUGGING:
ERROR: 1   funcAbort()
ERROR: 2   ()
ERROR: 3   gsignal()
ERROR: 4   abort()
ERROR: 5   __gnu_cxx::__verbose_terminate_handler()
ERROR: 6   ()
ERROR: 7   ()
ERROR: 8   __gxx_personality_v0()
ERROR: 9   ()
ERROR: 10   _Unwind_Resume()
ERROR: 11   Alignment::createBootstrapAlignment(int*, char const*, int*)
ERROR: 13   GOMP_parallel()
ERROR: 14   performAUTest(Params&, PhyloTree*, double*, std::vector<TreeInfo, std::allocator<TreeInfo> >&)
ERROR: 15   evaluateTrees(Params&, IQTree*, std::vector<TreeInfo, std::allocator<TreeInfo> >&, std::vector<int, std::allocator<int> >&)
ERROR: 16   reportPhyloAnalysis(Params&, IQTree&, ModelCheckpoint&)
ERROR: 17   runPhyloAnalysis(Params&, Checkpoint*)
ERROR: 18   main()
ERROR: 19   __libc_start_main()
ERROR: 20   _start()
ERROR: 
ERROR: *** IQ-TREE CRASHES WITH SIGNAL ABORTED
ERROR: *** For bug report please send to developers:
ERROR: ***    Log file: example.phy.log
ERROR: ***    Alignment files (if possible)
Aborted (degenerated `core' )

"""

As Kinggerm said, with 6.1 version it work perfectly. 
Cheers,
Carlos

**Comment by bqminh** [comment]
Hi Carlos,

The AU test is temporarily disabled as it’s unclear how it resolves numerical issue when bp-rell are zero. We’ll need to investigate this carefully before offering the test again. Thanks for your understanding

Minh
