### ISSUE TITLE
[PoMo] Decomposition of the rate matrix.

### ISSUE THREAD

**Issue by dschrempf** [Cibiv/IQ-TREE#79]
The function performing the eigendecomposition requests the rate matrix but also recomputes the rate matrix. This leaves room for speed improvements. `EigenDecomposition::eigensystem_sym()` expects a `matrix[][]` object with two indices. However, it is not used, because `ModelPoMo::computeRateMatrix()` is called anyways from within `eigensystem_sym()`.

    ./model/modelpomo.cpp:1091:        // TODO DS: This leaves room for speed improvements.

**Comment by bqminh** [comment]
Dominik, a comment on this: The 1.7 beta version now uses Eigen3 library for this purpose. This is much more stable and faster. eigensystem_sym() will be marked deprecated. Have a look at modelmarkov.cpp, decomposeRateMatrix() for reversible models and decomposeRateMatrixNonrev() for non-reversible models.
I suggest that you switch to this function, instead

**Comment by dschrempf** [comment]
Hi Minh,

thanks for letting me know. I just use ModelMarkov::decomposeRateMatrix() now,
and it seems to work quite well! I pushed the code to the pomo_latest branch, in
case you want to double check!

Maybe we should merge this branch back to latest anyways? What do you think?

Dominik

**Comment by bqminh** [comment]
Dominik, the code does not work correctly. Because decomposeRateMatrix() works with `rates` variable, whereas you worked with `rate_matrix` variable. I know this is confusing, and trying to resolve it. Will update once fixed.

**Comment by dschrempf** [comment]
Thanks, I was not aware of that. It is weird, because I did some tests and got
conclusive results. Maybe the parsimony trees were already good enough to
misguide me.

**Comment by bqminh** [comment]
The latest branch was updated. Can you please check that, Dominik? Make sure that the log-likelihood computation is correct, e.g. by comparing with a previous version.
Minh

**Comment by dschrempf** [comment]
Hi Minh,

thanks for working on this. I checked against version 1.6.10 from the homepage
and all looks good! Final log lh differs on third decimal. Both log files are
attached!

I will pull the code to the pomo latest branch also, in case you didn't do that
already.

Dominik

**Comment by bqminh** [comment]
cool, problem solved
