### ISSUE TITLE
[PoMo] Maximum distance

### ISSUE THREAD

**Issue by dschrempf** [Cibiv/IQ-TREE#80]
The distance measure of PoMo includes not only mutations (which can be compared to substitutions) but also frequency shifts. Hence, the branch lengths of PoMo are expected to be longer by a factor of `N*N`. This clashed with constants defined, e.g., in `tools.h`

   ./utils/tools.h:437:/* TODO DS: For PoMo, this setting does not make sense.
   ./utils/tools.cpp:861:    // TODO DS: This seems inappropriate for PoMo.  It is handled in
     
I had to manually recompute `MAX_GENETIC_DIST` whenever it is used, because during maximization of the likelihood, branch lengths were limited. This should be working now, but it is important to keep in mind when changing code in these areas. Maybe, a model dependent maximum distance may make sense.

**Comment by bqminh** [comment]
Alright. But as far as I see, you already handled this issue properly right? (e.g. by using max_genetic_dist var).

**Comment by dschrempf** [comment]
Hi Minh, yes I guess we can close this. I just thought it may make sense for other models too, then the model dependent maximum distance would have made sense; but maybe PoMo is a little bit of an exception in this respect!
