### ISSUE TITLE
[PoMo] Do not temper with `Params`

### ISSUE THREAD

**Issue by dschrempf** [Cibiv/IQ-TREE#81]
The problem is the following: when running IQ-TREE with PoMo, certain parameters need to be known already when reading in the alignment file (counts file at the moment). This is, the virtual population size `N` which affects the data structure and the sampling method (sampled or weighted). At the moment, those flags are stored in `ModelPoMo` upon model creation and also in the `Params` class. It may be advantageous to refrain from using the `Params` class to store model parameters.

    ./alignment/alignment.cpp:2085:    // TODO DS: Do not temper with params;

**Comment by bqminh** [comment]
let's close this issue, to clean up the list. sorry
