### ISSUE TITLE
[PoMo] Theta and sampling method sampled

### ISSUE THREAD

**Issue by dschrempf** [Cibiv/IQ-TREE#82]
The calculation of `theta` (Watterson's theta or level of polymorphism) is necessarily faulty, especially when `N` is low. I am not sure how to tackle this because the problem is of statistical nature.

    ./model/modelpomo.cpp:772:        // TODO DS: This is wrong because Watterson's estimator is

**Comment by bqminh** [comment]
Since this has been added 2 years ago and no progress, I'm gonna close this issue
