### ISSUE TITLE
How to add support value the the tree without rerun iq-tree?

### ISSUE THREAD

**Issue by yech1990** [Cibiv/IQ-TREE#84]
I known there is a argument `-sup` for assigning support value in tree output, I forget to add this argument in a previous run.

It seems that there is a file, `xxx.split.nex`, recording the bootstrap result, but I don't know how to render such file, and convert split record into support value in tree file.

Is it possible to transform `xxx.split.nex` into `xxx.suptree` without rerun iq-tree?

```
  Split support values:  xxx.splits.nex
```

**Comment by bqminh** [comment]
Hi, this question was asked in the IQ-TREE forum https://groups.google.com/forum/#!topic/iqtree/9AbMScqjwxo <https://groups.google.com/forum/#!topic/iqtree/9AbMScqjwxo>.  The short answer is yes, you can:

iqtree -sup xxx.treefile yyy.splits.nex

Will assign support values from splits file onto tree file.

Minh

**Comment by yech1990** [comment]
Thank you @bqminh 

It works as expected. But the label  on the suptree file is weird.

Instead of being `67/100`, the label is in `X1/X2` format (like `69/69`), where X1 is always equal to X2. 

![image](https://user-images.githubusercontent.com/5415510/45609969-d108c200-ba8c-11e8-8b1b-fb57ba40417c.png)

**Comment by bqminh** [comment]
Right this should be asked in the forum, Thus issue closed.

**Comment by yech1990** [comment]
Sorry for asking question in the wrong place.

Problem is solved.
