### ISSUE TITLE
Use entire FASTA header ID including text after space

### ISSUE THREAD

**Issue by sjackman** [Cibiv/IQ-TREE#85]
Does IQ-TREE have an option to use the entire FASTA header ID including the text after the space?

FastTree for example has a `-quote` option.
```
  -quote -- allow spaces and other restricted characters (but not ' ) in
           sequence names and quote names in the output tree (fasta input only;
           FastTree will not be able to read these trees back in)
```

**Comment by bqminh** [comment]
There is no such option, sorry. IQ-TREE will just ignore everything in the name after the first space.
