### ISSUE TITLE
Handling of Windows style file path in partition file

### ISSUE THREAD

**Issue by reslp** [Cibiv/IQ-TREE#92]
Hi,

First of all, thank you for all your work on IQ-TREE! It is a great piece of software and my number one tree inference program.
Therefore, I have been working on a cross-platform graphical user interface for it which I hope it will be useful for people with litte command-line experience or for teaching.

In the course of this, I have run into a problem with how iqtree parses NEXUS partition files on Windows. When iqtree parses a NEXUS file containing an absolute path to an alignment file it is unable to find the file. It seems iqtree treats the : character in the path as a separator between the alignment and the positions which should be analyzed. Here is a simplified example:

```
#NEXUS
begin sets;
charset part1=C:\Users\User\alignment\alignment_small.fas:*;
end;
```

The corresponding iqtree command looks like this:
```
C:/Users/User/Desktop/iqtree/iqtree.exe -nt AUTO -spp C:/Users/User/partitions.nex -m MFP -redo
```

When execute this command I get the following output:

```
IQ-TREE multicore version 1.6.8 for Windows 64-bit built Oct 28 2018
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.

Host:    WinDev1802Eval (AVX2, 1 GB RAM)
Command: C:/Users/User/Desktop/iqtree/iqtree.exe -nt AUTO -spp C:/Users/User/partitions.nex -m MFP -redo
Seed:    810529 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Mon Dec 03 00:21:21 2018
Kernel:  AVX+FMA - auto-detect threads (1 CPU cores detected)

Reading partition model file C:/Users/User/partitions.nex ...
NOTE: No CharPartition defined, use all CharSets

Loading 1 partitions...
Reading alignment file C ... ERROR: File not found C
```

If I run this on Linux or MacOS (with absolute paths) there are no problems.

all the best,

Philipp

**Comment by bqminh** [comment]
Hi Philipp,

Your GUI project sounds cool. Let me know once you are done, and I’ll announce it on the IQ-Tree web site.

Regarding Windows path, this colon ‘:’ is indeed a problem, and we overlooked when designing the nexus file. It is used as separator between alignment file name and the position specification. Right now I don’t really have a good solution. But maybe you can replace : by a special escaped character? But I don’t have an idea about that under Windows. I personally haven’t used Windows for 10 years or more.

Minh

**Comment by reslp** [comment]
Hi Minh,

Thank you for the information and your quick response! I will of course keep you informed about the status of the GUI project, I would like to have it (more or less) finished soon.

I have done some testing on this already before I posted here and I could not find a way to escape the character or use a different character instead. I also don't use Windows. All this comes from tests in a VirtualBox with Windows10. Are you using the Nexus Class Library to parse the NEXUS file? If so, maybe I can find something there on how to escape certain characters. 
I guess for the GUI I could also write some workaround code (e.g. copying alignment files to the working directory or so) but this is probably not optimal. If I find a solution for this I will let you know.

best,

Philipp

**Comment by bqminh** [comment]
I assume we can't do anything from IQ-TREE side, and the GUI should do something to overcome it. For example, remove "C:" from the file path, if the current drive is C.
