### ISSUE TITLE
Make Error: unrecognized option `-msse2avx'

### ISSUE THREAD

**Issue by shengwang** [Cibiv/IQ-TREE#93]
Linux: uname -a
Linux manger-server 2.6.18-308.4.1.el5_lustre #1 SMP Fri Jun 8 12:45:26 PDT 2012 x86_64 x86_64 x86_64 GNU/Linux

Cmake info:

-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- Check for working C compiler: cc
-- Check for working C compiler: cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: c++
-- Check for working CXX compiler: c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
IQ-TREE flags :
Builde mode   : Release
Target OS     : Unix
Compiler      : GNU Compiler (gcc)
Target binary : 64-bit
OpenMP        : Yes
MPI           : NONE
Vectorization : SSE3/AVX/AVX2
C flags       :  -pthread  -O3 -g -ffunction-sections -fdata-sections
CXX flags     :  -std=c++11 -fopenmp -pthread  -O3 -g -ffunction-sections -fdata-sections
LINKER flags  :  -rdynamic  -Wl,--gc-sections
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for getrusage
-- Looking for getrusage - found
-- Looking for GlobalMemoryStatusEx
-- Looking for GlobalMemoryStatusEx - not found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for strtok_r
-- Looking for strtok_r - found
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /lustre/pub/include
-- Found ZLIB: /Anaconda3-4.3.0/lib/libz.so (found version "1.2.8")
Using system zlib
-- Found Eigen3: /eigen-eigen-bdd17ee3b1b3 (Required is at least version "2.91.0")
-- Configuring done
-- Generating done
-- Build files have been written to: IQ-TREE-1.6.9/build

**Comment by bqminh** [comment]
Hi Sheng,

I couldn’t see any error message pasted below… where did that occur? 

Minh

**Comment by bqminh** [comment]
Since there is no further message from the original poster, I assume it was resolved
