### ISSUE TITLE
Write partition trees to the .treefile

### ISSUE THREAD

**Issue by crotty** [Cibiv/IQ-TREE#94]
When fitting an edge-unlinked partition model with -sp option, IQ-TREE does not write the branch lengths for each partition to the .treefile, or in the .iqtree file by default. Using the -v option the individual partition trees are written to the .iqtree file, but if the user wants to do anything with them they must be parsed from this file. It would be good if the trees for each partition were printed on a separate line in the .treefile and if the information on each partition was printed to .iqtree by default, rather than requiring the -v option.

**Comment by bqminh** [comment]
Hi Stephen, How about an option to print the partition trees? Or do you want to have these printed by default?

Minh

**Comment by bqminh** [comment]
Done in latest branch (v1.7-beta10 or higher). For -sp option a file .parttrees will be printed
