### ISSUE TITLE
Write Transfer bootstrap expectation (TBE) to .treefile

### ISSUE THREAD

**Issue by Matt-BF** [Cibiv/IQ-TREE#97]
Hello!
After reading about TBE and trying it out as a standalone package and with the newest IQ-Tree beta, I would like to know if it is possible to write the resulting support on the final `.treefile`, similarly as its done for aLRT values.
My solution has been to script this task manually, or to use `iqtree -sup [tbe_tree] -t [treefile]`

Also a follow-up question, is it valid to use TBE with UFBootstrap? From what I've seen, it was designed to correct non-parametric boostrap, but nothing on the publication has been said about UFBoot (which I've implemented fully into my pipelines, mainly because of the long time it takes for non-parametric bootstrap on larger groups).

Thanks in advance!
Matt

**Comment by bqminh** [comment]
Hi Matt,

This has been discussed. In fact we don’t recommend to use TBE in conjunction with UFBoot:

https://groups.google.com/forum/#!topic/iqtree/ULJmzhRr4zA <https://groups.google.com/forum/#!topic/iqtree/ULJmzhRr4zA>

Minh

**Comment by Matt-BF** [comment]
Hi Minh, thanks for the answer!
My thoughts when opening this issue were kind of the same as what [JPF asked](https://groups.google.com/d/msg/iqtree/ULJmzhRr4zA/0XzYamj_AQAJ), when reading your (great) paper on UFBoot and UFBoot2, the only correction I found discussed was about resolving politomies. Would that be enough to invalidate using TBE with UFBoot?
Maybe it is better to close this issue and take the discussion back to the group?
Thanks again!
Matt
