### ISSUE TITLE
Are gap/missing/ambiguous sites excluded in the calculations of branch lengths?

### ISSUE THREAD

**Issue by zhangrengang** [Cibiv/IQ-TREE#98]
or the full alignment length is used?

**Comment by bqminh** [comment]
Hi, 

gaps and missing characters have no influence in the estimation of branch lengths.

Ambiguous characters will influence, because they carry information, e.g. R means A or G, not C and T.

Cheers,
Minh

**Comment by matrs** [comment]
Someway related to this, when building a tree with `iqtree`, is it needed to remove from my MSA **columns with only gaps** or can I leave them?

**Comment by bqminh** [comment]
You can remove those columns with only gaps. But having them in there does not influence the inference, i.e. you should get the same result whether or not removing gap only columns or not.

Minh

**Comment by matrs** [comment]
Thanks!
